### ISSUE TITLE
Transfer into the jenkinsci org.

### ISSUE THREAD

**Issue by dblock** [jenkinsci/ansicolor-plugin#100]
Reduce bus factor, currently I am the only one who can add admins to this repo.

**Comment by dblock** [comment]
The transfer is done, @JoeMerten would you please adjust the POM accordingly as you are releasing the next version? Appreciate it.

**Comment by JoeMerten** [comment]
done

**Comment by JoeMerten** [comment]
However, need to check if there need to update RELEASING.md because of the migration.
Will be checked during the next release.
