### ISSUE TITLE
No color after update on 0.5.0

### ISSUE THREAD

**Issue by vit1251** [jenkinsci/ansicolor-plugin#102]
Hello,
Update jenkins and ansicolor and have no more colors and parameters AnsiColor.
How to determine what's problem with?
Thenks.

**Comment by dblock** [comment]
@vit1251 which version of Jenkins please? /cc: @JoeMerten

**Comment by vit1251** [comment]
@dblock version Jenkins is 2.51

**Comment by vit1251** [comment]
Downgrade on 0.4.3 no settings item in project and no color.

**Comment by vit1251** [comment]
Could you suggest plugin dependency. I am remove previously HTML support from Jenkins it may affect?

**Comment by dblock** [comment]
There should be no plugin dependency, in 0.5.0 we removed a dependency on Jansi. Try with 0.5.0 and restart jenkins? Anything in the logs on start?

**Comment by JoeMerten** [comment]
> Update jenkins and ansicolor and have no more colors and parameters AnsiColor.

What Jenkins and AnsiColor versions before?

**Comment by vit1251** [comment]
@dblock hmm... some about ansi color ...

`
Mar 20, 2017 11:33:35 AM hudson.plugins.ansicolor.PluginImpl start
INFO: AnsiColor: eliminating boring output (https://github.com/dblock/jenkins-ansicolor-plugin)
`

**Comment by vit1251** [comment]
@JoeMerten some like 2.49 or some like that... AnsiColor like 0.4.3. This problem with other plugins I am remove HTML and BlueOcean plugins.

**Comment by vit1251** [comment]
@JoeMerten @dblock I am sorry. Some disable AnsiPlugin on Jenkins Plugin Manager.
