### ISSUE TITLE
Release 0.5.1

### ISSUE THREAD

**Issue by dblock** [jenkinsci/ansicolor-plugin#103]
There're some startup changes and fixes, and a location change.

**Comment by dblock** [comment]
Maybe @mkobit as the latest contributor wants to help with this?

**Comment by mkobit** [comment]
@dblock I'll take a look at it today (or tonight).

**Comment by mkobit** [comment]
The `RELEASING.md` is great and easy to follow.
Condensing what I think needs to be done here:

- [ ] Create Jenkins CI account at https://jenkins-ci.org/account
- [ ] Get encrypted password from https://repo.jenkins-ci.org5webapp/#/profile and enter into the `~/.m2/settings.xml`
- [ ] Get r/w permissions to [github.com/jenkinsci/ansicolor-plugin](https://github.com/jenkinsci/ansicolor-plugin) with same GitHub username
- [ ] Get listed as developer in [jenkins plugin-ansicolor.yml](https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-ansicolor.yml)
- [ ] `mvn test` to verify tests
- [ ] Ensure pom version is correct and ends with `-SNAPSHOT`
- [ ] Update _"Next Release"_ section in CHANGELOG.md to correct date and version
- [ ] Commit changes your next release
    ```
    git add CHANGELOG.md
    git commit -m "Preparing for release, 0.4.1"
    git push origin master
    ```
- [ ] Make sure directory is clean and run `mvn release:prepare release:perform`.
  Follow interactive steps to release `0.5.1`
- [ ] Prepare for the next release
    ```
    0.5.2 (Next)
    ============
    
    * Your contribution here.
    ```
    ```
    git add CHANGELOG.md
    git commit -m "Preparing for next development iteration"
    git push origin master
    ```

Some of these steps require access permissions. I'm not going to have time today to do most of this but can do it tomorrow night.

**Comment by dblock** [comment]
Happy to grant permissions as necessary.

**Comment by mkobit** [comment]
Closed in https://github.com/jenkinsci/ansicolor-plugin/commit/1f04f4f3c521d8325ea19dfc1a2e17d9a3c8a835 , https://github.com/jenkinsci/ansicolor-plugin/commit/056b8e39941d876d25220ea602093c73a8c8ae38 , https://github.com/jenkinsci/ansicolor-plugin/commit/b2e8135c2e58b74e98025ad29b389087354bb7e6 , https://github.com/jenkinsci/ansicolor-plugin/commit/5b2b4606760e54d9b6d47dea17e0b2ad6b4951d2
