### ISSUE TITLE
`colorMapName` is not optional in declarative pipeline

### ISSUE THREAD

**Issue by rochdev** [jenkinsci/ansicolor-plugin#106]
### Test environment

- Jenkins Version: 2.46.1
- AnsiColor Version: 0.5.0
- Hostsystem: Amazon Linux (ECS)

### Expected behavior

In declarative pipeline, `colorMapName` parameter should be optional like in scripted pipeline.

### Actual behavior

Build fails with:

```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 92: Missing required parameter: "colorMapName" @ line 92, column 21.
                       ansiColor {
                       ^

```

### Steps to reproduce the behavior

In a declarative pipeline:

```
ansiColor {
    // anything
}
```

**Comment by dblock** [comment]
Looks reasonable. Please feel free to PR a fix.

**Comment by rochdev** [comment]
This should be fixed by https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/145

I will try when it lands and report back

**Comment by tszmytka** [comment]
The `colorMapName` parameter has been optional for a long time now.
