### ISSUE TITLE
I have pure JS version

### ISSUE THREAD

**Issue by jakubjosef** [jenkinsci/ansicolor-plugin#110]
Hi everyone,
sorry for creating an issue for this, but lot of people have issues with this plugin, and there is no need to patch the output on server, so i created pure JS version of this plugin, because we really want to have colorised output.
Enjoy! https://github.com/jakubjosef/jenkins-ansi-color-js

**Comment by dblock** [comment]
I would welcome a README section called "Other Implementations" or "Alternatives" and you could list this there? PR please.

**Comment by tszmytka** [comment]
There's been no interest in over 3 years
