### ISSUE TITLE
Python Radish bdd tool crashes entire Jenkins job when coloring ansi output with AnsiColor 0.5.1

### ISSUE THREAD

**Issue by davidghiurco** [jenkinsci/ansicolor-plugin#112]
### Test environment

- Jenkins Version: 2.22
- AnsiColor Version: 0.5.1
- Hostsystem: Cent-OS

### Expected behavior

python radish bdd tool (A BDD testing tool for python, mimics Cucumber for Java -- installable with pip install radish-bdd) uses ansi coloring and it prints test scenarios colorfully to console

I'm unable to provide screenshots as they would contain proprietary information from my company's Jenkins build server.

We were trying to debug why our BDD test tool was crashing so badly without any warning all of a sudden (It worked yesterday). Turns out the Ansi color plugin was updated yesterday and introduced a regression. Turning off Ansi coloring in Jenkins re-enables the Job and it runs fine, but console output obviously looks terrible since there are un-interpreted ANSI symbols all over the place

### Actual behavior

It seems the upgrade from 0.5.0 to 0.5.1 creates some sort of regression when radish tries to print things to console in Jenkins. Note that Ansi coloring still works with cucumber (The Java bdd tool)

### Steps to reproduce the behavior

"Please provide small but complete code, e.g. shell script and / or Jenkinsfile"

As mentioned above, I am unable to provide any such code because it contains proprietary information :\ However, if you install the radish tool (https://github.com/radish-bdd/radish) and write a sample test and try to run it in the Test environment mentioned above, when you will run the radish command, the job will finish with an error, and there will be no console output past the command you just ran, not even a "Execute shell step marked build as failure"....It just fails. I was able to recreate the issue we were having in our builds which test our software following these steps

**Comment by dblock** [comment]
Try to see what ANSI sequence is causing the failure and maybe write a test that reproduces it in this repo?

**Comment by davidghiurco** [comment]
Since I'm not getting any output once radish runs, I am assuming that the first ansi characters Jenkins tries to render with the new 0.5.1 are causing issues. As indicated in the readme included in this zip, downgrading the version back to 0.5.0 fixed the issue.

Attached with instructions on how to run test.

[ansi_problems.zip](https://github.com/jenkinsci/ansicolor-plugin/files/1218917/ansi_problems.zip)

**Comment by pmhahn** [comment]
Me to:

> SCHWERWIEGEND: A thread (/bin/sh -xe /tmp/hudson1533679972336805410.sh: stdout copier/203506) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
> java.lang.IllegalStateException: Attribute 10 should not be reached
>         at hudson.plugins.ansicolor.AnsiHtmlOutputStream.processSetAttribute(AnsiHtmlOutputStream.java:469)
>         at hudson.plugins.ansicolor.AnsiOutputStream.processEscapeCommand(AnsiOutputStream.java:361)
>         at hudson.plugins.ansicolor.AnsiOutputStream.write(AnsiOutputStream.java:138)
>         at hudson.plugins.ansicolor.AnsiHtmlOutputStream.write(AnsiHtmlOutputStream.java:220)
>         at java.io.FilterOutputStream.write(FilterOutputStream.java:125)
>         at hudson.plugins.ansicolor.AnsiColorConsoleLogFilter$1.eol(AnsiColorConsoleLogFilter.java:51)
>         at hudson.console.LineTransformationOutputStream.eol(LineTransformationOutputStream.java:60)
>         at hudson.console.LineTransformationOutputStream.write(LineTransformationOutputStream.java:56)
>         at hudson.console.LineTransformationOutputStream.write(LineTransformationOutputStream.java:74)
>         at java.io.PrintStream.write(PrintStream.java:480)
>         at hudson.util.StreamCopyThread.run(StreamCopyThread.java:61)

and later

> java.lang.NumberFormatException: For input string: "10m4.4.4.4"
>         at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
>         at java.lang.Integer.parseInt(Integer.java:492)
>         at java.lang.Integer.<init>(Integer.java:677)
>         at hudson.plugins.ansicolor.AnsiOutputStream.write(AnsiOutputStream.java:133)

This is caused by 2c09afa6729dc952a8fb99eeb9f23c15ae37cfdc, which now throws an IllegalStareException() instead of ignoring unknown attributes.
See <https://en.wikipedia.org/wiki/ANSI_escape_code#graphics>

From <https://www.npmjs.com/package/ansi-escape-sequences> I guess its

> fontDefault	string	"\u001b[10m"

Proposed patch at 5f76947cdc7c7d74e5c2b64bb3f9bc66e3cd82c5

**Comment by dblock** [comment]
Can you please try with 0.5.2 that just got released?

**Comment by grayaii** [comment]
Will do. I'll let you know how it goes (I'm testing the issue that I created, which is related to this: https://github.com/jenkinsci/ansicolor-plugin/issues/113).  I'll let you know how it goes!

**Comment by grayaii** [comment]
Works like a charm! Thank you so much for fixing this!

**Comment by dblock** [comment]
👍
