### ISSUE TITLE
Relese v. Next

### ISSUE THREAD

**Issue by dblock** [jenkinsci/ansicolor-plugin#115]
@mkobit Do you think you could do this? It includes the fix in #114

**Comment by mkobit** [comment]
Yup, I'll take care of this tonight.

**Comment by mkobit** [comment]
Will actually do this today.

**Comment by mkobit** [comment]
Released in https://github.com/jenkinsci/ansicolor-plugin/commit/63fa4774107258f37b43aefb573708c385dd7fbb
