### ISSUE TITLE
Version 0.5.1 stopped working in  Jenkins  LTS 2.60.2

### ISSUE THREAD

**Issue by krulls** [jenkinsci/ansicolor-plugin#116]
Please provide precise details of the issue you detected.
Console output of builds stop printing. The loading wheel disappears. However the build run keeps working and after a while the build finishes and has a status but the log is incomplete.

### Test environment

- Jenkins Version: 2.60.2
- AnsiColor Version: 0.5.1
- Hostsystem: CentOS 6.4

We found the bug in projects using NodeJS (and the NodeJS plugin 0.2.2), so this is probably related.

### Expected behavior
build log should be complete.

### Actual behavior
build log incomplete.

### Steps to reproduce the behavior
guess you need a job with colored log output, then run and follow the console output.

### Our workaround
We downgraded to version 0.5.0, which is working fine with LTS 2.60.2

**Comment by dblock** [comment]
Is this the same issue as #114?

**Comment by krulls** [comment]
I guess yes. [#114](https://github.com/jenkinsci/ansicolor-plugin/pull/114) is very technical, so I am not sure. But there is #112(https://github.com/jenkinsci/ansicolor-plugin/pull/112) linked as well and this sounds very similar to our experience.﻿

**Comment by dblock** [comment]
Can you please try with 0.5.2 that just got released and close this if it's fixed?

**Comment by krulls** [comment]
just tested 0.5.2 with latest Jenkins LTS 2.60.3 on a FreeStyle Project with NodeJS plugin environment:
successful!
