### ISSUE TITLE
document detection of ansicolor wrapper presence in pipelines

### ISSUE THREAD

**Issue by ssbarnea** [jenkinsci/ansicolor-plugin#117]
When using in pipelines we need some groovy code that detects if the wrapper was loaded or not. That is very important for writing shared-librares that would enable or not ANSI features based on that.

I am not sure if we can rely on `if ('xterm' in env.TERM) { ... }` as safe way to detect that you can use ANSI features.

In either case we need to have this documented.

**Comment by Lucas-C** [comment]
`env` cannot be access inshared libs.
A detection method that would also work in shared libs would be awesome.

**Comment by Lucas-C** [comment]
I have found this solution which also work from inside a shared lib, provided `this.steps` is provided (_e.g._ in [`vars/`](https://github.com/voyages-sncf-technologies/hesperides-jenkins-lib/blob/master/vars/hesperides.groovy#L51)) :
```groovy
import hudson.EnvVars
import org.jenkinsci.plugins.workflow.steps.EnvironmentExpander

def env = EnvironmentExpander.getEffectiveEnvironment(new EnvVars(), null, steps.getContext(EnvironmentExpander.class), null, null)
def ansiColorEnabled = 'TERM' in env
```

**Comment by Lucas-C** [comment]
For the record, my initial attempt was to call `steps.sh(script:'echo $TERM', returnStdout: true).trim()`, but this does not work outside a `node {}`

**Comment by ssbarnea** [comment]
I am no longer using Jenkins, so feel free to close it if nobody else asks abou it.
