### ISSUE TITLE
Add ansiColor as an option

### ISSUE THREAD

**Issue by tnguyen14** [jenkinsci/ansicolor-plugin#118]
Instead of wrapping each of the `stage() { steps { } }` of my Jenkinsfile pipeline with `ansiColor('xterm')`, is it possible to declare it as a pipeline `options` https://jenkins.io/doc/book/pipeline/syntax/#options ?

I'm aware that this might require a change deep within Jenkins core, and out of the control of this plugin.

**Comment by agabrys** [comment]
@dblock Hello, You added the `needs more info` label to the task. What information do you need?

**Comment by dblock** [comment]
It doesn't seem like this is something we can do from the plugin, at least according to the OP, so this needs issues on Jenkins or someone who understands how this can be done.

**Comment by agabrys** [comment]
I understand. I know that `timestamps` option works so I compared [TimestamperStep](/jenkinsci/timestamper-plugin/blob/master/src/main/java/hudson/plugins/timestamper/pipeline/TimestamperStep.java) with [AnsiColorStep](/jenkinsci/ansicolor-plugin/blob/master/src/main/java/hudson/plugins/ansicolor/AnsiColorStep.java). Unfortunately, I didn't found any difference which could cause the problem.

@StevenGBrown is the author of the Timestamper plugin. Maybe we could ask him for help?

**Comment by brushmate** [comment]
For me `ansiColor('xterm')` is working as an option. But I had to add some additional Maven configuration in order to get colored Maven output:

    pipeline {
        agent {
            label 'my-build-node'
        }
    
        options {
            ansiColor('xterm')
        }
    
        environment {
            MAVEN_OPTS = '-Djansi.force=true'
        }
    
        stages {
            stage('Example') {
                steps {
                    sh "./mvnw -Dstyle.color=always -B verify"
                }
            }
        }
    }

**Comment by FanchTheSystem** [comment]
I confirm it look like it work now ...

**Comment by willis7** [comment]
I can confirm this works

**Comment by ilanni2460** [comment]
@agabrys i have same the promble

`  options {
    buildDiscarder(logRotator(numToKeepStr: '20'))
    timestamps()
    ansiColor('xterm')
  }`

**Comment by eyalg1972** [comment]
When I try adding-

options {
        ansiColor('xterm')
    }

    environment {
        MAVEN_OPTS = '-Djansi.force=true'
    }

And then-

stage ('Build stage')
		{
			steps {
			
				bat 'mvn -version'

				bat 'mvn -Dstyle.color=always -B clean install'	
		
			}

It does not work, when I use Maven 3.5.4 and JDK 1.8 of IBM on WIndows

Eyal

**Comment by jensmaurer** [comment]
Confirmed: `options { ansiColor('xterm') }` does the right thing. So, the present feature request is moot.

**Comment by dblock** [comment]
@jensmaurer Can you help document this (PR)? What do we need to close this issue?

**Comment by agabrys** [comment]
I would like also to confirm that
```
options {
    ansiColor('xterm')
}
```
works. Having this example on:
* https://jenkins.io/doc/book/pipeline/syntax/#options
* https://plugins.jenkins.io/ansicolor

would be great.

If I'm right then
* Jenkins Syntax uses this data: https://github.com/jenkins-infra/jenkins.io/edit/master/content//doc/book/pipeline/syntax.adoc
* https://plugins.jenkins.io/ansicolor displays the same information as https://wiki.jenkins.io/display/JENKINS/AnsiColor+Plugin

🙂

**Comment by tszmytka** [comment]
The possibility to enable the plugin using `options` has been working for several months now. It is documented in the [readme](https://github.com/jenkinsci/ansicolor-plugin#pipeline)
