### ISSUE TITLE
No ANSI Color in Jenkins test reports

### ISSUE THREAD

**Issue by breun** [jenkinsci/ansicolor-plugin#120]
The Jenkins AnsiColor plugin seems to be working nicely, but it does not seem to influence standard output captured in test reports.

### Test environment

- Jenkins Version: 2.73.3
- AnsiColor Version: 0.5.2

### Expected behavior

I would have expected standard output in test reports to be colorized.

### Actual behavior

I see output like this (at a URL like https://jenkins.example.com/job/example-job/2798/testReport/com.example.package/TestClass/Name_of_test/):

```
?[2m2017-12-11 13:57:25.398?[m ?[32m INFO?[m ?[2m[    Test worker]?[m ?[36mo.s.t.c.s.AbstractContextLoader         ?[m ?[2m:?[m ?[39mCould not detect default resource locations for test class [...[truncated 14870 chars]...
```

### Steps to reproduce the behavior

I don't have anything prepared right now, but this happens when tests use ANSI colored logging.

**Comment by JoeMerten** [comment]
I also used xunit and AnsiColor within the same project. For my experience, I'd observed that xunit failed parsing if there are escape sequences with in the xml file. 

For your setup, I suggest that there is some piece of software within your tooling or in Jenkins / xunit / junit which substitutes the `esc` char code 27 by `?` to make the xunit / junit parser work.

So finally for the first sight, it looks not like an issue which is addressed to AnsiColor plugin.
Please check if your above mentioned output differs when running the job without AnsiColor plugin.

**Comment by ben-lei-gfm** [comment]
Can you show an example of how to work around this?

Or can someone modify Ansicolor to handle this?

**Comment by elamre** [comment]
Does anybody have a workaround for this?

**Comment by NielsenAnders** [comment]
It is an actual issue - JUnit XML files containing colorized system out text, parses correctly but is not displayed with any color.  Snip from actual pipeline with the plugin enabled for the whole pipeline. The console log is correctly colorized.

![pipelihe_tc](https://user-images.githubusercontent.com/115548904/220570369-b68bf29f-ef6b-4e81-b54c-ea6a571c805c.PNG)
![pipelihe_console](https://user-images.githubusercontent.com/115548904/220570765-bdc76870-e365-43fc-8f1b-f4e7394fbeab.PNG)
