### ISSUE TITLE
Backgroud color disappears for extended/truncated console outputs

### ISSUE THREAD

**Issue by vbekkerm** [jenkinsci/ansicolor-plugin#124]
For builds that produce a lot of output, Jenkins truncates the output and displays only the bottom portion with a link to the full log at the top.

When this happens, AnsiColor stops displaying the overall background color and only the Jenkins default background color is displayed.  However, AnsiColor still colors each individual newly produced log line, making it very difficult to read, since the overall color scheme is now broken.

If, however, the full output is displayed (by clicking on the link at the top to show the full log), that page has the correct background color over the entire AnsiColor's colored scope.

It looks like the problem is the overall div that AnsiColor creates for the colored output.  When Jenkins truncates the output, the beginning div tag (where the background color is defined) is cut off, resulting in the broken background color.  When the full console output is displayed, the beginning div tag is part of the HTML code and everything works properly.

### Test environment

- Jenkins Version: 2.115
- AnsiColor Version: 0.5.2
- Hostsystem: Docker container running Alpine Linux

### Expected behavior

The correct background color over the AnsiColor display scope, regardless of any truncation.

### Actual behavior

When Jenkins truncates the output and displays only the bottom portion, AnsiColor stops displaying the overall background color and only the Jenkins's default background color is displayed.

### Steps to reproduce the behavior

Use AnsiColor with a background color different that Jenkins default on any build that produces a lot of output, so that Jenkins truncates it.

**Comment by henzef** [comment]
For me all colors disappear when jenkins truncates the log output (ansicolor 0.7.1). It worked in 0.6.2

**Comment by jonni83** [comment]
This issue fixed for me with the most recent update.  compared to builds from yesterday, color is now working on the same jobs with very long logs (6600KB+).

Jenkins Version: 2.250
AnsiColor Version: 0.7.2
Host System: RedHat 7.8
