### ISSUE TITLE
Release v. Next

### ISSUE THREAD

**Issue by dblock** [jenkinsci/ansicolor-plugin#131]
@dwnusbaum Want to take a stab?

See https://github.com/jenkinsci/ansicolor-plugin/blob/master/RELEASING.md

**Comment by dwnusbaum** [comment]
I filed https://github.com/jenkins-infra/repository-permissions-updater/pull/919 for release permissions. Have you already given me write permission to this repo?

**Comment by dwnusbaum** [comment]
Ok, I will do some manually testing to double check everything and hopefully release the next version sometime today.

**Comment by dwnusbaum** [comment]
@jglick mentioned to me that he was reevaluating the difficulty of the `ConsoleAnnotatorFactory` fix mentioned in https://github.com/jenkinsci/ansicolor-plugin/pull/128#issue-226995822, so I am holding off on this for now.

**Comment by dwnusbaum** [comment]
New PR is up as #132, but it requires a another baseline update, so I am going to release what we currently have for now, and will review the new PR afterwards.

**Comment by dwnusbaum** [comment]
Completed by e74935e6e, e90480b17, b7618ad44, and 0a28a9ae7.
