### ISSUE TITLE
Colors are not displayed immediately after upgrading to 0.6.0

### ISSUE THREAD

**Issue by michelzanini** [jenkinsci/ansicolor-plugin#136]
### Test environment

- Jenkins Version: 2.151
- AnsiColor Version: 0.6.0
- Hostsystem: Linux

### Expected behavior

When a pipeline build is triggered, if I immediately open the logs as soon as I trigger `Build Now`, the colors for that build won't appear while I am tailing the logs on Jenkins.
If I press back on the browser, open the same build logs again, the logs appear in colors.
I am using a declarative pipeline and using `ansiColor('xterm')` inside `options`.

### Actual behavior

The colors should appear always. Reverting the plugin to 0.5.3 fixes the issue.

### Steps to reproduce the behavior

Create a pipeline with `ansiColor('xterm')` inside `options`.
Press build now and go fast to Console output. I believe you need to get there before the `ansiColor` option is executed.
The logs won't display colors anymore. It will display again if you go back and open logs a second time.

**Comment by jglick** [comment]
Presumably related to #132. I had not observed anything like this.

**Comment by reinholdfuereder** [comment]
I have to confirm this issue: refreshing the console log (in classic UI) e.g. via pressing F5 is necessary.

**Comment by kapoorlakshya** [comment]
Hi, I am also experiencing this when using Cucumber and plugin version 0.6.2 (latest). I see the control characters and no colors in the console output as the text shows up. However, when I refresh the page the control characters disappear and the text shows up in color. 

This behavior is not experienced in v0.5.3. Also, this only happens in the classic console output and not in the Blue Ocean view.

Before refresh:

![image](https://user-images.githubusercontent.com/4314581/52154485-e42ebf80-2632-11e9-9bb7-7bda260698cf.png)


After page refresh:

![image](https://user-images.githubusercontent.com/4314581/52154497-f01a8180-2632-11e9-8e66-e7db76663725.png)

Raw output:

```
[32mAnd I access the '[32m[1mSearch[0m[0m[32m' [32m[1mtab[0m[0m[32m[90m
```

Pipeline code:

```
      steps {
        ansiColor('xterm') {
          dir(path: 'cucumber-watir') {
            bat(script: 'bundle exec cucumber -t %tags% -f json -o cucumber.json -f pretty --color --expand')
          } // dir
        } // ansiColor
      } // steps```

**Comment by tlvu** [comment]
I have current latest Jenkins LTS 2.150.3 with AnsiColor 0.6.2 and I also observe same behavior as @kapoorlakshya .  Before refresh I see control characters and no colors. After refresh the colors are displayed properly, no garbage control character.  In classic console output.  Preferred classic console to the new blue ocean so did not even install the blue ocean.

**Comment by e-moshaya** [comment]
any update on this issue?

**Comment by dblock** [comment]
Waiting for your fix @e-moshaya!

**Comment by pietervogelaar** [comment]
If a job starts and I reload the page before about 5 seconds, the page is still not colorized. If I wait about 10 seconds before reload, than it's indeed colorized. So it looks like a race condition or a problem with the timing of the ansi color plugin initialization.

**Comment by vishmegh88** [comment]
We are still seeing the issue with 0.6.2 version of plugin and CloudBees Jenkins Enterprise 2.164.3.2-rolling. 

Steps to Repro are same as above. After refreshing the page colors appear.

**Comment by jglick** [comment]
> CloudBees Jenkins Enterprise 2.164.3.2-rolling

@vishmegh88 if you are a CloudBees customer, please open a support ticket.

**Comment by vishmegh88** [comment]
@jglick this plugin is a third party plugin, I opened a ticket with Cloudbees, but the best they can do is help us diagnose the problem and provide us with workarounds, which they say we can do by downgrading the plugin. 

We are still facing this issue, and it hampers the our user experience and can lead to incorrect assumptions for our users. 

Is there any timeline to fix this issue.

**Comment by pietervogelaar** [comment]
Downgrading the plugin doesn't work well for Blueocean.

**Comment by vishmegh88** [comment]
@pietervogelaar Haven't tried that, but what are the issues that you are seeing with blueocean after downgrading.

**Comment by JiffsMaverick** [comment]
I had same issue.

Jenkins 2.176.3
AnsiColor 0.6.2

**Comment by siwyd** [comment]
I'm experiencing the same behavior with the plugin. I regularly need to refresh the page for the colors to appear.

**Comment by DavidPerezIngeniero** [comment]
I used to have version 0.5.2 and worked flawlessly

**Comment by DavidPerezIngeniero** [comment]
Reverted to version 0.5.2 and works ok. :-)

**Comment by reinholdfuereder** [comment]
@DavidPerezIngeniero IIRC the changes were necessary for (better?) support of colours in/by new/modern Blue Ocean UI; cf. @pietervogelaar's comment:

> Downgrading the plugin doesn't work well for Blueocean.

**Comment by DavidPerezIngeniero** [comment]
Luckily I don't need Blue Ocean.

**Comment by jglick** [comment]
I can reproduce. https://github.com/jenkinsci/ansicolor-plugin/blob/77677c7609135fbda8029c85c35d4dd5c9bf4c8d/src/main/java/hudson/plugins/ansicolor/ColorConsoleAnnotator.java#L160-L164 only works if you start displaying the log after the `ansiColor` block is entered.

**Comment by dwnusbaum** [comment]
I just released 0.6.3, notably including #171, which should fix this issue, and #168 (should fix #151 and maybe some other issues that were lacking enough info to reproduce).

**Comment by Binternet** [comment]
Not working for me as well.

Jenkins 2.231
ansiColor 0.6.3

**Comment by Hello-Linux** [comment]
Me too
Jenkins 2.222
ansiColor 0.7.0

**Comment by knope** [comment]
Same problem 
Jenkins 2.235.1
ansiColor 0.7.0

**Comment by krulls** [comment]
seems like this issue should be reopened. is that even possible with github issues :thinking: ?

**Comment by dblock** [comment]
I reopened it since lots of people are having issues.

**Comment by dblock** [comment]
Actually https://github.com/jenkinsci/ansicolor-plugin/issues/193 supersedes it.

**Comment by krulls** [comment]
> Actually #193 supersedes it, please help debug the issue over there.

From my POV it would be a better approach to mark #193 as a duplicate and leave #136 open since here you have a lot of participants who loose track otherwise.
