### ISSUE TITLE
Outputs from shared lib is not colorized

### ISSUE THREAD

**Issue by ThilinaManamgoda** [jenkinsci/ansicolor-plugin#138]
Please provide precise details of the issue you detected.

### Test environment

- Jenkins Version: 2.151
- AnsiColor Version: 0.6.0
- Hostsystem: Apache tomcat 9.0

### Expected behavior

Colorized outputs from shared library. 

### Actual behavior

Outputs from a shared library is not colorized. 
### Steps to reproduce the behavior

Create a shared library with the following class and use the pipline script provided.

Class: 

class Utilities implements Serializable {
    def steps
    Utilities(steps) {this.steps = steps}
    def color() {
        steps.ansiColor('xterm') {
            steps.echo "Hello \\u001B[31mRed\\u001B[m"
        }
       
    }
}

Pipeline:

@Library("lib") import org.example.Utilities
def utils = new Utilities(this)
node {
     stage("Test") {
        utils.color()
    }
}

**Comment by tinyzimmer** [comment]
I'll just chime in here and say I _think_ I'm seeing this behavior too? Essentially, I have a shared lib that defines some pipelines and common steps used across our repos. I've tried moving the wrapper everywhere.

Whether in options:

```
        options {
            buildDiscarder(logRotator(numToKeepStr:'10'))
            disableConcurrentBuilds()
            ansiColor('xterm')
        }
```

Or the step level

```
ansiColor('xterm') {
    sh "echo some colorful output"
}
```

It doesn't just flat out not work. It's just extremely inconsistent. It'll work once, and then nothing will change and subsequent builds will stop colorizing output and just dump the escape codes. I was looking for an issue similar here, but saw this one referring to shared libraries too so figured I'd chime in.
