### ISSUE TITLE
BO pipeline view "header line" shows escape sequences for echo step

### ISSUE THREAD

**Issue by reinholdfuereder** [jenkinsci/ansicolor-plugin#140]
Thanks to https://github.com/jenkinsci/ansicolor-plugin/pull/132 using `ansiColor` wrapper step nicely shows colours in classic UI as well as Blue Ocean (👍): however, in BO the `echo` steps "header line" in pipeline view also contains the escape sequences.

### Test environment

- Jenkins Version: 2.152
- AnsiColor Version: 0.6.0

### Expected behavior

Presumably just the plain (non-colourized) text from echo step with truncation like now, just WITHOUT any escape sequences?

### Actual behavior

![grafik](https://user-images.githubusercontent.com/145182/48888623-91b37480-ee33-11e8-8c49-331570c51003.png)

### Steps to reproduce the behavior

```
ansiColor('xterm') {
  echo "\033[1;31mPipeline problem: \033[0m That might be the reason"
}
```

**Comment by jglick** [comment]
Best to close and reopen in JIRA for `blueocean-plugin`. If it is processing ANSI sequences in the main console block view, it should at least _strip_ them when producing summaries.

**Comment by reinholdfuereder** [comment]
@jglick OK, thanks for the hint => https://issues.jenkins-ci.org/browse/JENKINS-54875 (I also added the forgotten hint that this problem was there before AnsiColor 0.6.0 already)
