### ISSUE TITLE
Escape sequences of echo steps in build log show up in notification emails that include last lines of build log with v0.6.0

### ISSUE THREAD

**Issue by reinholdfuereder** [jenkinsci/ansicolor-plugin#141]
Thanks to #132 using ansiColor wrapper step nicely shows colours in classic UI as well as Blue Ocean (👍): however, in notification emails that include (e.g. the last N) build log lines these escape sequences are also shown.

### Test environment

    Jenkins Version: 2.152
    AnsiColor Version: 0.6.0

### Expected behavior

![grafik](https://user-images.githubusercontent.com/145182/48905151-0bae2280-ee61-11e8-982e-371bdbabbe4c.png)

Please note that the red colouring of this line is explicitly done in the Groovy email template by hand (based on some grep-ing for certain keywords at the start of the line)...
Frankly I would not mind, if this is done automagically: conversion of console annotator formating to HTML in HTML emails, but maybe that is bit unrealistic ;-)

### Actual behavior

![grafik](https://user-images.githubusercontent.com/145182/48905061-c12ca600-ee60-11e8-81b8-bc2fabfad4a8.png)

### Steps to reproduce the behavior

Email based on email-ext and Groovy template containing logic like:
```
...
List<String> logLines = build.getLog(50)
logLines.each() { line ->
%>
  <TR class="${cssClass}">
    <TD>${org.apache.commons.lang.StringEscapeUtils.escapeHtml(line)}</TD>
  </TR>
<%
...
```

Or here: https://github.com/jenkinsci/email-ext-plugin/blob/afb5983a7bc9b718480c05fc94a52d39e1405d37/src/main/resources/hudson/plugins/emailext/templates/groovy-html.template#L246-L249

**Comment by jglick** [comment]
I guess the `mailer` and/or `email-ext` plugins could be either stripping ANSI sequences, or converting them to HTML, or running the log tail through `AnnotatedLargeText` to convert to HTML (with the caveat that this will in general require loading of some CSS and JavaScript side files which would not be appropriate for email).
