### ISSUE TITLE
Newline produces wild results

### ISSUE THREAD

**Issue by DarrienG** [jenkinsci/ansicolor-plugin#150]
Using a newline within an set of ansi escape codes horribly breaks output.

### Test environment

- Jenkins Version:
2.162
- AnsiColor Version:
0.6.0 (but even wilder results on 0.6.1)

- Hostsystem:
CentOS 7
Slaves run jnlp slave

### Expected behavior
Color formatted lines and _only_ formatted lines.

Like so:

![image](https://user-images.githubusercontent.com/5041953/52240769-d5007980-289f-11e9-8c43-f3f5fd1f7e37.png)

### Actual behavior
Everything is colored after a newline. Exit escape sequence is never honored.
<img width="922" alt="screen shot 2019-02-04 at 5 11 30 pm" src="https://user-images.githubusercontent.com/5041953/52240812-fa8d8300-289f-11e9-945f-3abdcd7cdc01.png">

### Steps to reproduce the behavior

Use a newline in a set of ansi escape sequences.

```bash
#!/usr/bin/env bash
green() { echo -e "\033[0;32m${1}\033[0m"; }

green "some number of stuff"
echo "i am the next string"

totalTests=10
green "\n$(basename $0) ran successfuly, tests were run."

echo -e "Hey"
echo -e "There"
```

In a shell running bash 4+, this colors correctly, but with ansicolor, everything below the newline is green and irreversibly colored.

Version 0.6.1 is affected even worse than this, and produces some very strange results.

<img width="1228" alt="screen shot 2019-02-04 at 5 14 26 pm" src="https://user-images.githubusercontent.com/5041953/52240932-607a0a80-28a0-11e9-88c1-47fa44e3dbdf.png">
^ from version 0.6.1

We recently upgraded from version 0.5.7 and did not have this issue.

**Comment by DarrienG** [comment]
Update - we've continued looking into this, and we think any escape character may just break it. We'll continue our investigation.

**Comment by dwnusbaum** [comment]
0.6.0 and 0.6.1 have problems in this area (e.g., #135, #145). I think 0.6.2 should fix it as a result of #137/#147.

**Comment by DarrienG** [comment]
Thanks - we'll give it a shot at our next maintenance cycle and report back.

**Comment by tszmytka** [comment]
@DarrienG Did you have a chance to review if the issue has been fixed?

**Comment by DarrienG** [comment]
Apologies, I don't work where I used to work at the same place anymore. I think some of my old coworkers may know.

@yhrenlee do you know if the Jenkins folks are still having trouble with ansicolor and escape sequences? I seem to remember this was fixed.
