### ISSUE TITLE
Is the wrapper needed?

### ISSUE THREAD

**Issue by nadimkhemir** [jenkinsci/ansicolor-plugin#152]
Hi, I though all output would be scanned for ANSI codes and this plugin would colorize without any other  needed action (except installing it). Now I read about the wrappers in the documentation, are those a must?

Cheers N.

**Comment by dwnusbaum** [comment]
As far I am aware, yes, the wrapper is required. If you are interested in working on the plugin, I think it would be possible to implement some kind of global configuration that would automatically do [the same thing as the `ansiColor` step](https://github.com/jenkinsci/ansicolor-plugin/blob/ff2264aa5d96ab819f96b904fec1766d529d194b/src/main/java/hudson/plugins/ansicolor/AnsiColorStep.java#L74-L83) for all Pipeline builds. It looks like that feature request is already tracked as https://github.com/jenkinsci/ansicolor-plugin/issues/2.
