### ISSUE TITLE
Escape codes aren't working for me

### ISSUE THREAD

**Issue by ORESoftware** [jenkinsci/ansicolor-plugin#157]
These work in bash on my various machines:

```bash
export ntrs_gray='\033[1;30m'
export ntrs_magenta='\033[1;35m'
export ntrs_cyan='\033[1;36m'
export ntrs_orange='\033[1;33m'
export ntrs_yellow='\033[1;33m'
export ntrs_green='\033[1;32m'
export ntrs_red='\033[31m'
export ntrs_no_color='\033[0m'

```

so I would use like so:

```bash
echo -e "${ntrs_magenta} process is exiting with code $exit_code. ${ntrs_no_color}";
```

but this doesn't seem to work with this plugin on Jenkins (yes I checked the box for ansi colors on the job and the advertised red color does work.)

This does work for me on jenkins:

```bash
printf "\e[31mHello World\e[0m\n"
```

Is there a way for you to put the color codes in the readme? It's probably fairly in demand to use them the way I did above? Idk

**Comment by tszmytka** [comment]
@ORESoftware All the escape sequences you mention work with `ansicolor-plugin` correctly. Your one-liner also correctly displays the text in color.
Can you please provide:
* Jenkis version
* ansicolor-plugin version
* log of the job where it `doesn't seem to work`

**Comment by tszmytka** [comment]
Closing as it is impossible to reproduce without additional information.
