### ISSUE TITLE
python behave no color output

### ISSUE THREAD

**Issue by tavisdxh** [jenkinsci/ansicolor-plugin#160]
Please provide precise details of the issue you detected.

### Test environment

- Jenkins Version:  2.176.2
- AnsiColor Version: 0.6.2
- Hostsystem: CentOs

### Expected behavior

Run behave testcase in server, we can get color output. And behave support ansi color by default.

![{7F89BD4F-7F9E-41DB-B8B6-935974FE403A}_20190725111001](https://user-images.githubusercontent.com/12155033/61843024-cdc03d00-aecc-11e9-929d-a3bc367733a0.jpg)

### Actual behavior

If we run testcase in jenkins job which config ansi color output in build step with the same command, there is no color output. But ansi color plugin works fine with demo statement.

The bellow command works fine:
printf "\e[31mHello World\e[0m\n"
printf "Normal \e[1mBold\e[0m\n"
printf "Normal \e[4mUnderlined\e[0m\n"
![{9987A461-4339-44EB-A59E-5A76F45A2814}_20190725111849](https://user-images.githubusercontent.com/12155033/61843407-10cee000-aece-11e9-832d-9ae38b31020b.jpg)

### Steps to reproduce the behavior

Run testcase command:
behave features/test_case/  -D DB_HOST=127.0.0.1  --no-capture --junit

**Comment by tszmytka** [comment]
@tavisdxh Could you please provide the actual output from your `behave` command?
For example contents of the `output.txt` file from
```
behave features/test_case/ -D DB_HOST=127.0.0.1 --no-capture --junit > output.txt
```

**Comment by tszmytka** [comment]
Closing as it is impossible to reproduce without additional information.

**Comment by tavisdxh** [comment]
@tszmytka Apologize for my delay response.
![微信截图_20200610182608](https://user-images.githubusercontent.com/12155033/84257424-e3237180-ab47-11ea-864a-4c43cf08343b.png)

[output.txt](https://github.com/jenkinsci/ansicolor-plugin/files/4757833/output.txt)
