### ISSUE TITLE
Release v. Next

### ISSUE THREAD

**Issue by dblock** [jenkinsci/ansicolor-plugin#166]
Who wants to do it?

@ejelly @dwnusbaum ?

Go for it ;)

**Comment by v-lopez** [comment]
I have no idea how to do it, but I can be a tester if you need. 
I have seen a lot of movement lately on the repo and we'd love a release with https://github.com/jenkinsci/ansicolor-plugin/pull/168

**Comment by dwnusbaum** [comment]
I just released 0.6.3, most notably including #168 (should fix #151 and maybe some other issues that were lacking enough info to reproduce) and #171 (should fix #136)
