### ISSUE TITLE
default background, and foreground color escape code not working

### ISSUE THREAD

**Issue by nhatkhai** [jenkinsci/ansicolor-plugin#175]
I have my console using default background escape code \e[49m, and foreground \e[39m. The escape code seem to work, but also show up itself  in the console after reset to default colors.
![image](https://user-images.githubusercontent.com/8029988/80026869-d623c380-84b0-11ea-9aa5-6c15fae6d4ea.png)
![image](https://user-images.githubusercontent.com/8029988/80026886-dc19a480-84b0-11ea-916c-bf5d1337924e.png)

**Comment by tszmytka** [comment]
I don't quite get what you mean by 
> I have my console using default background escape code \e[49m, and foreground \e[39m
How exactly do you set that?


Also please provide the following:
- Build script or Jenkinsfile which triggers the issue for you, at the very least its raw output.
- Jenkins Version
- AnsiColor Version
- Hostsystem

**Comment by nhatkhai** [comment]
```
sh """echo "\e[42m\e[97mHELLO\e[49m\e[39m Should be default color, and background" """
```

**Comment by tszmytka** [comment]
> I do not know what my company use for versioning, here are my best

your best what?

If you are running Jenkins on Windows Server then your script will **not** run without additional non-standard settings ([`sh` step doesn't work on Windows](https://issues.jenkins-ci.org/browse/JENKINS-33708)) in your pipeline (what are they).

Your example put into a simplistic pipeline:
```
ansiColor {
    echo '\033[42m\033[97mHELLO\033[49m\033[39m Should be default color, and background'
}
```
works fine :
![snip1](https://user-images.githubusercontent.com/60844785/80864702-9749f680-8c84-11ea-8cb5-0b990da6c5c5.png)

on
* Jenkins 2.164.3
* AnsiColor 0.6.3

Please set up such a pipeline on your system and post the output.

**Comment by tszmytka** [comment]
Closing as it is impossible to reproduce without additional information.
