### ISSUE TITLE
256 color mode not displaying correctly in 0.7.0

### ISSUE THREAD

**Issue by salavessa** [jenkinsci/ansicolor-plugin#186]
When using escape codes for the [256-color space](https://en.wikipedia.org/wiki/ANSI_escape_code#8-bit), the output doesn't behave as expected on `0.7.0` (worked ok on `0.6.3`)

### Test environment

- Jenkins Version: `2.222.3`
- AnsiColor Version: `0.7.0`
- Hostsystem: `Linux x64`

### Expected behavior
Expecting that text color in jenkins console would output same/similar colors as observed visible in a terminal:
![expected](https://user-images.githubusercontent.com/15344273/82958526-75a30d00-9fad-11ea-9bc1-38ebb8566305.png)

### Actual behavior
The text gets some format applied but it's not the expected (first line `Bold Blue`, second line `Bold Magenta`):
![actual-0 7 0](https://user-images.githubusercontent.com/15344273/82958132-9b7be200-9fac-11ea-864f-814e960771da.jpg)

### Steps to reproduce the behavior
`printf '\e[1;38;5;4m[fe1.k8sf.atom.us-west-2 ]\e[0m\n\e[1;38;5;13m[fe1b.k8sf.atom.us-east-2]\e[0m'`

**Comment by tszmytka** [comment]
Can reproduce.
Thank you especially for the escape sequence example - it's already in a test case.
A fix will follow up shortly.
