### ISSUE TITLE
No colored output for maven build

### ISSUE THREAD

**Issue by Hello-Linux** [jenkinsci/ansicolor-plugin#189]
Please provide precise details of the issue you detected.

### Test environment

- Jenkins Version: Jenkins 2.222
- AnsiColor Version: 0.7
- Hostsystem: centos7

my pipeline is
```
 stage('build') {
      steps {
        ansiColor('xterm') {
          container('maven') {
            sh 'echo -e "\033[41;30m红底黑字\033[0m"'
            sh 'mvn clean install -Dmaven.test.skip=true -Dmaven.compile.fork=true -T 1C'
          }
        }
      }
    }
```
but echo has color  and maven has no color output
![2020-06-03 15-24-06 的屏幕截图](https://user-images.githubusercontent.com/17851645/83607823-7855c180-a5ae-11ea-8084-4e1142c5622a.png)

**Comment by tszmytka** [comment]
What you are seeing has nothing to do with `ansicolor` plugin:
1. Your screenshot comes from `Blue Ocean` UX/UI. It does all the escaping/rendering on its own.
2. The fact that your `echo` example shows colors proves that you most likely haven't set up `maven` command with appropriate settings. Have you tried `-Dstyle.color=always`?

Either way I am going to go ahead and close this unless you have a real classical UI `ansicolor` plugin issue.
