### ISSUE TITLE
Console output is not colorized

### ISSUE THREAD

**Issue by keltik85** [jenkinsci/ansicolor-plugin#199]
Please provide precise details of the issue you detected.

### Test environment

- Jenkins Version: 2.90
- AnsiColor Version: 0.6.3
- Hostsystem: Debian GNU/Linux 9 (stretch)

### Expected behavior
I expected that running the example colorizes my console output:
```groovy
pipeline {
    agent any
    options {
        ansiColor('xterm')
    }
    stages {
        stage('Build') {
            steps {
                sh 'something that outputs ansi colored stuff'
            }
        }
    }
}
```

### Actual behavior
It does not colorize my console output.

### Steps to reproduce the behavior
I think you need to match the specific versions of Jenkins, Plugin and Host and use the snipped provided above.

**Comment by tszmytka** [comment]
I think you forgot to post your actual pipeline. The current one comes from
the example from Readme file.
Please update the description and also provide a screen shot of what you
think i wrong.

**Comment by keltik85** [comment]
> I think you forgot to post your actual pipeline. The current one comes from the example from Readme file. Please update the description and also provide a screen shot of what you think i wrong.

No, even the example is not wokring.

**Comment by tszmytka** [comment]
The example doesn't produce any ansi escape codes on its own.
You are supposed to use an actual command instead of 'something that
outputs ansi colored stuff'.
Something like (from the Readme) `printf "\e[31mHello World\e[0m". This
command depends on your OS/stack so you need to find something that also
works directly in your shell.

**Comment by keltik85** [comment]
Oh, i thought it would produce the same output i get when running the commands inside my Linux bash. Sorry.

**Comment by dblock** [comment]
It can be confusing to new users, @keltik85 care to PR an update to README to replace the example with an actual ANSI sequence?
