### ISSUE TITLE
Allow global setting

### ISSUE THREAD

**Issue by ctrabold** [jenkinsci/ansicolor-plugin#2]
The plugin is very useful. The only thing that's nagging me is, that I have to enable it in every job. Given I have > 100 Jobs, this gets quite cumbersome ;)

What do you think about a global switch for enabling it per default?

**Comment by tpot** [comment]
I use a wrapper in Jenkins Job builder to ensure that the plugin is enabled for all my jobs:

http://docs.openstack.org/infra/jenkins-job-builder/wrappers.html

**Comment by dblock** [comment]
@tpot It would be great to document this in README somehow, please contribute!

**Comment by dsaita** [comment]
Try this script:

def jobs = hudson.model.Hudson.instance.items

jobs.each { job ->

    def has_color_wrapper = false
    job.buildWrappersList.each { wrapper ->
      if (wrapper instanceof hudson.plugins.ansicolor.AnsiColorBuildWrapper) {
        has_color_wrapper = true
        println("$job.name is already configured.")
      }
    }
    if (!has_color_wrapper) {
      	println("Adding AnsiColor to $job.name")
      	job.buildWrappersList.add(new hudson.plugins.ansicolor.AnsiColorBuildWrapper());
    	job.save()
    }
}

**Comment by tknerr** [comment]
+1, especially in the context of Jenkins 2.x Pipeline builds a global setting would be super useful. Enabling colored output is a cross-cutting concern that you may not want to repeat in each and every `Jenkinsfile`.

Will give @dsaita 's workaround a try...

**Comment by tknerr** [comment]
Another approach I was thinking about was redefining the [`sh` step](https://jenkins.io/doc/pipeline/steps/workflow-durable-task-step/#sh-shell-script) from within a [global library](https://github.com/jenkinsci/workflow-cps-global-lib-plugin), but

1. my groovy foo is a bit outdated and first experiments not successful
2. I don't know if redefining pipeline DSL steps would work at all or is guarded against somewhere

**Comment by subos2008** [comment]
If we can't have a truly global setting - can we have a one liner for pipeline jobs that doesn't use a block? I'm new to pipeline but having all these wrapper blocks seems a bit ridiculous.

**Comment by ericfrancis** [comment]
@subos2008 were you able to find a solution?

**Comment by subos2008** [comment]
@ericfrancis not yet. Perhaps the declarative style makes it easier, but our pipelines aren't simple enough to use declarative style at the moment.

**Comment by ericfrancis** [comment]
@subos2008 I was able to wrap all with:

#!groovy
```
pipeline {
  agent any

  options {
    buildDiscarder logRotator(daysToKeepStr: '5')
    timeout(time: 10, unit: 'MINUTES')
    ansiColor('xterm')
  }
```

**Comment by subos2008** [comment]
@ericfrancis Yep, that's the new declarative style for pipelines.  Vastly improves this kind of thing. However, the declarative style is (currently) much more limited. A solution for the traditional groovy script would be much appreciated - which is what this thread is about. (aiui)

**Comment by Sh-Ho** [comment]
Any progress on this issue?

**Comment by nickbroon** [comment]
An equivalent global config was added to the timestamper plugin here:
https://github.com/jenkinsci/timestamper-plugin/commit/1afb7d4b4077c7aa7660794d75e018def8ba08c0

It would be great to see a global config option for ansicolor

**Comment by dblock** [comment]
Please contribute!

**Comment by hashar** [comment]
Thank you @kcboschert :+1:

**Comment by zxti** [comment]
Hi, would you consider cutting a new release so we can use this great feature? Thanks!

**Comment by dblock** [comment]
> Hi, would you consider cutting a new release so we can use this great feature? Thanks!

https://github.com/jenkinsci/ansicolor-plugin/issues/166
