### ISSUE TITLE
Raw escape sequences in output while refreshing a long running build

### ISSUE THREAD

**Issue by tszmytka** [jenkinsci/ansicolor-plugin#200]
There's still a situation where it's not working correctly so I made up a somewhat contrived pipeline script.

```groovy
pipeline {
  agent any

  options {
    ansiColor('xterm')
  }

  stages {
    stage('Run') {
      steps {
          echo '\033[32mcolored output\033[0m'
sh label: 'colors', script: '''echo start
for c in {30..37}; 
do
  printf "Time for $c\\n"
  sleep 3
  echo -e "\\e[31mHello World\\e[0m"
  echo -e "\\e[${c}m Loop $c \\e[0m"
  printf '\\033[32mcolored output\\033[0m\\n'
  printf "\\033[${c}mcolored output\\033[0m\\n" 
  for i in {000..199}
  do 
    printf "\\033[${c}mI\\\'m filler $i taking up a bunch of log space ####################################################################################\\033[0m\\n" 
  done
  echo next
done'''
    
    
      }
    }
  }
}
```

The problem for me now is when Jenkins truncates the output when it gets too long. 
After starting that pipeline mash refresh on the console output view every ~3 seconds. It's looping through colors 30 to 37 and at about 33 (refresh when it's on green) refreshing loses the color. I suspect it's hitting a case were an escape sequence is getting split by the console getting truncated and whatever is doing the parsing decides not to try past the invalid input but just a guess.
___
![Peek 2020-08-05 10-40 ansiColor](https://user-images.githubusercontent.com/5008161/89433584-21807b80-d708-11ea-8bb5-525ec9caaca0.gif)
Example where I hit refresh on the green step (there colors stop working) and then after it finishes (color works again).

Versions:
```
Jenkins 2.235.1
ansicolor 0.7.2
```

_Originally posted by @chder in https://github.com/jenkinsci/ansicolor-plugin/issues/193#issuecomment-669268756_

**Comment by tszmytka** [comment]
I can confirm this is a bug. I removed any mention of `Timerstamper` (it is not at fault here) to keep focus on the actual cause.

**Comment by tszmytka** [comment]
This is generalization of the problem described in #198  
It can be visible for any long-running job which produces enough output for the "truncate log" functionality to kick-in.

**Comment by perk11** [comment]
Can this please be released? Just upgraded to 0.7.2 and a lot of logs are displaying escape sequences instead of colors

**Comment by cedson** [comment]
I'm still seeing this non-colorized behavior with 'truncated' console output with Jenkins v LTS 2.249.2 and ansicolor-plugin v. 0.7.3

**Comment by vjrj** [comment]
Me too

**Comment by djtfmartin** [comment]
Me too with v2.266
