### ISSUE TITLE
Ansicolor not rendering ansi color codes in Jenkins output.

### ISSUE THREAD

**Issue by olivereri** [jenkinsci/ansicolor-plugin#206]
### Test environment
```
- Jenkins Version: Jenkins 2.233
- AnsiColor Version: 0.6.3
- Operating System running Jenkins: amd64 Linux 4.14.173-106.229.amzn1.x86_64
```

### Expected behavior

Jenkins pipeline calls Ansible to run a shell command with the shell module on a remote host. The shell runs an executable that returns ansi escape and color characters.  Expected output is Ansicolor plugin rendering color codes in to defined colored text.
![image](https://user-images.githubusercontent.com/31904439/93510724-8833b000-f8d6-11ea-9c31-4377565ce699.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/31904439/93511129-29226b00-f8d7-11ea-94d3-c255433f771a.png)
![image](https://user-images.githubusercontent.com/31904439/93511222-5111ce80-f8d7-11ea-9ae1-f5132791bb2f.png)
 
When the Ansible module returns output that includes Ansi color code characters, Ansicolor-plugin is not rendering them as it should.

### Steps to reproduce the behavior

Run ansible-playbook against a remote host
`ANSIBLE_FORCE_COLOR=true ANSIBLE_LOAD_CALLBACK_PLUGINS=1 ANSIBLE_STDOUT_CALLBACK=default ansible-playbook shell-script.yml`
The shell script should execute a command or program that produces text coloring in the output. e.g. printf, echo, ...
Ansible task output displayed in Jenkins will include output that contains unrenderred ansi color characters.

### Issue checklist

- [x] Jenkins version
- [x] AnsiColor version
- [x] Operating System name and version
- [x] Expected behavior
- [x] Actual behavior
- [x] Steps to reproduce the behavior

First step is to upgrade to version 0.7.3 to see if that fixes our current issue.

**Comment by tszmytka** [comment]
Thank you for a great issue description.
You are using a pretty outdated version of `ansicolor`. As you noticed on your own - please upgrade to the newest one and see if it helps.

**Comment by olivereri** [comment]
We've upgraded Jenkins to use 0.7.3 version of Ansicolor. However, we're still seeing the same behavior. Output from an Ansible tasks 'sdtout' field has unicode escape sequences with color codes that aren't being rendered. It's almost like nested color code sequences can't be rendered.

**Comment by olivereri** [comment]
Wanted to follow up with a more concise set of steps to reproduce what we've observed and ask more specific questions about this behavior:

These versions are slightly different than those in the initial issue description but the behavior is still observed.
Jenkins Version:                 2.249 (containerized)
Ansicolor-Plugin Version:   0.7.3
Ansible Version:                 2.9.13

Jenkins Pipeline Job Script:
```
pipeline {
    agent any

    options {
        ansiColor('xterm')
    }
    stages {

        stage('Deploy') {
            steps {
                sh 'ANSIBLE_STDOUT_CALLBACK=yaml ANSIBLE_LOAD_CALLBACK_PLUGINS=1 ANSIBLE_FORCE_COLOR=true ansible-playbook -i ../../../inventory -v ../../../shell-play.yml'
                
            }
        }
    }

}
```

Ansible-Playbook Script:
```
- name: Remote shell output
  hosts: docker-host 
  connection: local
  gather_facts: false
  tasks:
    - name: Run Shell Script
      shell: |
        printf '\u001b[31mhello world\u001b[0m'
```

Output:
![image](https://user-images.githubusercontent.com/31904439/93831868-c9a2c300-fc28-11ea-9046-ce084328c3cd.png)

Color coding for Ansible works great in the Jenkins log. However, rendering ansi color codes that come from Ansible Shell Module output isn't happening. The idea is to get Ansi Color coded feed back from commands that don't have a corresponding Ansible Module and can only be invoked by remote shell commands.

Does anyone have an idea of what might be going on here?
Does this have something to do with Ansible's callback plugins and how that information is sent back to Jenkins?
Is it that the ansicolor plugin can't render nested codes? 
Are these actually nested?

**Comment by tszmytka** [comment]
Can you run the same `sh` command directly in your shell, store the output and post it?
Something like
```
ANSIBLE_STDOUT_CALLBACK=yaml ANSIBLE_LOAD_CALLBACK_PLUGINS=1 ANSIBLE_FORCE_COLOR=true ansible-playbook -i ../../../inventory -v ../../../shell-play.yml > out.txt
```
Seems to me this might be an Ansible thing (might be wrong - I don't have much experience with it). It looks like your `\u001b` come already escaped and `ansicolor` has nothing to interpret there.

**Comment by olivereri** [comment]
Sure thing. Looking in VI I see a bunch of control characters that ansicolor does indeed eventually render correctly. Anything else isn't recognized.

```
^[[0;34mUsing /etc/ansible/ansible.cfg as config file^[[0m

PLAY [Remote shell output] ************************************************************************************************************************************************************************************

TASK [Run Shell Script] ***************************************************************************************************************************************************************************************
^[[0;33mchanged: [docker-host] => changed=true ^[[0m
^[[0;33m  ansible_facts:^[[0m
^[[0;33m    discovered_interpreter_python: /usr/bin/python^[[0m
^[[0;33m  cmd: |-^[[0m
^[[0;33m    printf '\u001b[31mhello world\u001b[0m'^[[0m
^[[0;33m  delta: '0:00:00.375070'^[[0m
^[[0;33m  end: '2020-09-22 20:07:28.508992'^[[0m
^[[0;33m  rc: 0^[[0m
^[[0;33m  start: '2020-09-22 20:07:28.133922'^[[0m
^[[0;33m  stderr: ''^[[0m
^[[0;33m  stderr_lines: <omitted>^[[0m
^[[0;33m  stdout: \u001b[31mhello world\u001b[0m^[[0m
^[[0;33m  stdout_lines: <omitted>^[[0m

PLAY RECAP ****************************************************************************************************************************************************************************************************
^[[0;33mdocker-host^[[0m                : ^[[0;32mok=1   ^[[0m ^[[0;33mchanged=1   ^[[0m unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
If I did want to have what Ansible returns to Jenkins in it's task callback to have color, would I need to do some processing to find \u001b, \033, and \e escape characters then replace them with escape sequence control characters?

**Comment by ElijahLynn** [comment]
hia, I'm working with @olivereri on this and we are looking at this now. I am crosslinking two issues on this:

https://github.com/ansible/ansible/pull/7487
https://github.com/ansible/ansible/issues/7522

It does seem like _maybe_ the stdout_callback plugin of Ansible is affecting this output and it seems like Ansible might be ripe for a patch to allow ANSI output to bubble up for the `shell` and `command` modules with a new config option. We may have to write a custom stdout_callback here and contribute it to here > https://github.com/ansible-collections/community.general/tree/main/plugins/callback.

**Comment by tszmytka** [comment]
> When Ansible sends the data back it may be escaping those escapes.

Exactly.


The following lines
```
^[[0;33m    printf '\u001b[31mhello world\u001b[0m'^[[0m
^[[0;33m  stdout: \u001b[31mhello world\u001b[0m^[[0m
```
confirm that this is indeed happening: `ESC` (shown as `^[`) gets properly interpreted by `ansicolor` but `\u001b` from your `yml` gets escaped somewhere along the way and ends up being printed verbatim and thus - not interpreted.

**Comment by olivereri** [comment]
I did just that. Debugged and stepped through what's happening:

![image](https://user-images.githubusercontent.com/31904439/94187834-62ba1f80-fe5d-11ea-9769-ea5a91367395.png)

`u'stdout` corresponds to the raw output that is saved in a results dictionary. The string it points to below is what will get printed to the console.  It looks like the `AnsibleUnsafeText` type when converted to a string makes sure to escape those sequences.

I'm Looking at how I might be able to allow those escapes to bubble up within Ansible so Ansicolor can do its work. Thanks for looking through this with us.
