### ISSUE TITLE
For some failure it not able to recognize

### ISSUE THREAD

**Issue by gudipudipradeep** [jenkinsci/ansicolor-plugin#208]
Some failure it could not able to recognize the issue.
![issue](https://user-images.githubusercontent.com/8638634/94690103-50545000-034d-11eb-8610-3108fa09635f.png)
for consoleText it showing as follows.
![consoleText](https://user-images.githubusercontent.com/8638634/94691401-dfae3300-034e-11eb-8e2c-ae54685a97a6.PNG)
it showing different characters

**Comment by dblock** [comment]
Recognize what?

**Comment by gudipudipradeep** [comment]
![log](https://user-images.githubusercontent.com/8638634/94691773-577c5d80-034f-11eb-95f2-d3e61c562b38.png)
Exist code is 1.

**Comment by dblock** [comment]
Why do you think this is an issue with ansicolor-plugin? You have an error accessing your SVN repository.

**Comment by gudipudipradeep** [comment]
I was thinking that if we have failure in logs, it will how the read color as per understanding.

**Comment by dblock** [comment]
> I was thinking that if we have failure in logs, it will how the read color as per understanding.

If the tool is emitting ANSI colors, then yes. Otherwise no, there's no magical coloring of errors. That's why I asked what the raw output looks like from that svn command. Does it include ANSI color codes?

**Comment by gudipudipradeep** [comment]
@dblock Yes, it is a raw text but it is not emitting any ANSI color.  I thought it was doing some regex and adding color so... thanks for @dblock

**Comment by dblock** [comment]
Nope, not magical. I'll close this, if you have ANSI codes not being rendered, do open a bug.
