### ISSUE TITLE
Read plugin global configuration using groovy example

### ISSUE THREAD

**Issue by Constantin07** [jenkinsci/ansicolor-plugin#209]
Hi,

This is rather a guidance or request for help.
I'm looking for a way to configure this plugin globally in Jenkins, not via UI but using Groovy in Jenkins Script Console so that I can bootstrap Jenkins at start up by placing the script under `init.groovy.d` directory.

Below is a snippet, I'm trying to get the plugin configuration but getting back `null`

```groovy
import jenkins.model.*
import hudson.plugins.ansicolor.*

// get Jenkins instance
def inst = Jenkins.getInstance()
def desc = inst.getDescriptor("hudson.plugins.ansicolor")
  
println(desc)
```

Please could someone advise how to read the global configuration for this plugin ?

**Comment by tszmytka** [comment]
I think this is what you are trying to get:
```
import jenkins.model.*
import hudson.plugins.ansicolor.*

// get Jenkins instance
def inst = Jenkins.getInstance()
def desc = inst.getDescriptor("hudson.plugins.ansicolor.AnsiColorBuildWrapper")
println(desc)
```
Result
```
hudson.plugins.ansicolor.AnsiColorBuildWrapper$DescriptorImpl@678b394c
```


Wouldn't [Jenkins Configuration as Code](https://www.jenkins.io/projects/jcasc/) be better for configuring everything?

**Comment by Constantin07** [comment]
Thanks @tszmytka for advice. I'm using a Jenkins with legacy Groovy scripts to bootstrap it and I don't know how it's gonna work together with JCasC. I will need to test how it works because I'm not sure that JCasC can replace all functionality written in Groovy.
