### ISSUE TITLE
Colorized log display is inconsistent between browsers.

### ISSUE THREAD

**Issue by daxgames** [jenkinsci/ansicolor-plugin#210]
### Test environment
```
- Jenkins Version: 2.249.3
- AnsiColor Version: 0.7.3
- Operating System running Jenkins:

jenkins@jenkins-6f4b894c5-kwrz2:/$ uname -a
Linux jenkins-6f4b894c5-kwrz2 4.14.198-152.320.amzn2.x86_64 #1 SMP Wed Sep 23 23:57:28 UTC 2020 x86_64 GNU/Linux
jenkins@jenkins-6f4b894c5-kwrz2:/$ cat /etc/issue
Debian GNU/Linux 9 \n \l
```

### Expected behavior

Colorize part of the Jenkins log.

This is new info related to: #180 and #181

### Actual behavior

Colorized parts of the Jenkins log in Chrome 86.0.4240.198 but not in Firefox 68.8.0esr for the same job build.

Chrome

![image](https://user-images.githubusercontent.com/7318053/99269073-eb1cc700-27f3-11eb-946e-1f3a9518dc30.png)

Firefox

![image](https://user-images.githubusercontent.com/7318053/99268983-d2acac80-27f3-11eb-9d2c-02bc94067b6f.png)

### Steps to reproduce the behavior

pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
                ansiColor('vga') {
                    sh 'ls -la'
                }
                echo 'Hello World'
                ansiColor('vga') {
                    sh 'ls -la'
                }
            }
        }
    }
}

### Issue checklist

- [X] Jenkins version
- [X] AnsiColor version
- [X] Operating System name and version
- [X] Expected behavior
- [X] Actual behavior
- [X] Steps to reproduce the behavior

**Comment by tszmytka** [comment]
You're comparing a recent Chrome with Firefox version released over 6 months ago. Not exactly apples to apples.
Checked manually - your pipeline displays correctly in Firefox >= 80.0 (haven't tried anything older).

Can't you install a newer version?
