### ISSUE TITLE
Output truncated with python colorful

### ISSUE THREAD

**Issue by bra-fsn** [jenkinsci/ansicolor-plugin#211]
I'm not sure if it's a bug in ansicolor-plugin itself, but at least the output differs from an xterm window.
The problem is the output gets truncated in the Jenkins output, while running the same command in a terminal, it displays fine.
I've opened https://github.com/timofurrer/colorful/issues/46 as well, because I think printing that `[26m` is the main culprit, but as I mentioned, the output looks just fine in a terminal.

### Test environment
```
- Jenkins Version: 2.260
- AnsiColor Version: 0.7.3
- Operating System running Jenkins: ubuntu 18.04
```

### Expected behavior

I would expect to see the same output as in a terminal.

### Actual behavior

Truncates the output:
![image](https://user-images.githubusercontent.com/820331/101909834-5ae95c00-3bbe-11eb-948d-02d57e531a89.png)

### Steps to reproduce the behavior

Python script to trigger it:
https://gist.github.com/bra-fsn/5f875a29bf043ae74748f2f9b2dbac81

**Comment by tszmytka** [comment]
Thanks for a detailed report. 
I can confirm this (`ESC[26`) is indeed not working at all in `ansi-color`. In fact the plugin never had any implementation for this sequence so it is less of a bug and more a new feature request.
I can't say yet if/how complex the implementation might be. I first need to find how it behaves, even the [wikipedia article](https://en.wikipedia.org/wiki/ANSI_escape_code) says
> ITU T.61 and T.416, not known to be used on terminals 

It seems it is pretty exotic.

Would you be able to post a screenshot from your terminal showing it in action with multiple lines of text?

**Comment by bra-fsn** [comment]
> Would you be able to post a screenshot from your terminal showing it in action with multiple lines of text?

Sure:
![image](https://user-images.githubusercontent.com/820331/102067912-0c290580-3dfc-11eb-9734-fcba78f30ace.png)

Here, the `Snapshotted step` lines got truncated (they should have more info after the `in 1`).

**Comment by tszmytka** [comment]
Thanks but I think you posted the incorrect output coming from Jenkins log (this is useful on its own).

What I was interested to see is your actual terminal (bash/putty etc.) showing how the **correct** output should look like.
Sorry for not being clear on that.

**Comment by bra-fsn** [comment]
@tszmytka oh, I haven't responded to this, sorry about that.
Trying to add everything to the context again.
So here's what I can see (the whole output is bigger, I've just extracted a small part of it) in the Jenkins output:
![image](https://user-images.githubusercontent.com/820331/123107422-d19ec600-d439-11eb-9602-6fe3a2a5dcd5.png)
And this is what I can see, when I issue a `cat /tmp/color1`:
![image](https://user-images.githubusercontent.com/820331/123107589-f7c46600-d439-11eb-855a-bf6f60de9985.png)

Also attaching the file itself:
[color1.txt](https://github.com/jenkinsci/ansicolor-plugin/files/6702247/color1.txt)

Running Jenkins 2.290 and ansicolor 0.7.5 ATM.
