### ISSUE TITLE
Logs not showing colors 

### ISSUE THREAD

**Issue by avihaycloudinary** [jenkinsci/ansicolor-plugin#212]
### Test environment
```
- Jenkins Version:2.263.1
- AnsiColor Version:0.7.3
- Operating System running Jenkins: Ubuntu 14.04.6 LTS
```

### Expected behavior
see logs similar to full log screen 
![image](https://user-images.githubusercontent.com/73224983/102991861-c0c0d680-4522-11eb-81a9-098b2404dd6a.png)

### Actual behavior
Logs not showing colors (do show in Full log mode/screen),
![image](https://user-images.githubusercontent.com/73224983/102991778-8f480b00-4522-11eb-91e3-ebea651a162f.png)

### Steps to reproduce the behavior
free style project, 
execute shell 
echo '\033[42m\033[97mWhite letters, green background\033[0m'
 
![image](https://user-images.githubusercontent.com/73224983/102915533-a6d3b500-448a-11eb-9e7b-2d0f197ad34e.png)
![image](https://user-images.githubusercontent.com/73224983/102987085-805d5a80-451a-11eb-98b8-2da48c2cf04a.png)
![image](https://user-images.githubusercontent.com/73224983/102987244-b995ca80-451a-11eb-81ae-72c1716d1149.png)

### Issue checklist

- [x] Jenkins version
- [x] AnsiColor version
- [x] Operating System name and version
- [x] Expected behavior
- [x] Actual behavior
- [x] Steps to reproduce the behavior

**Comment by tszmytka** [comment]
Thanks for the issue. Two things:

1. Your example on how to reproduce doesn't reveal any bugs.
Your `echo` doesn't produce an escape character so there are no ANSI codes to interpret. Try running it in a regular shell - you will get the exact same result.
The following should be able to render colored output in the shell as well as Jenkins Console Output.
   ```
   echo -e '\033[42m\033[97mWhite letters, green background\033[0m'
   ```
   Can you please confirm?

2. Disable `timestamper`.
The description mentions differences between truncated and full output. Additionally I can see you are using `timestamper` plugin. This combination used to cause problems in the past. Which `timestamper` version are you using?
Could you try disabling it, running your job and posting the results?

**Comment by avihaycloudinary** [comment]
Many thanks for your answer,
The shell worked just fine (with timestamp)

We are using `timestamper 1.11.8`
I will disable it and let you know the result

**Comment by avihaycloudinary** [comment]
Disabling the `timestamper` did not fix it.
The behaviour is strange, it is showing the colors till the log become 2 big and this message appears 
`Skipping 13 KB.. Full Log`
![image](https://user-images.githubusercontent.com/73224983/103356177-e1f06c80-4ab8-11eb-924d-a6ce3779c2d3.png)

![image](https://user-images.githubusercontent.com/73224983/103356115-b4a3be80-4ab8-11eb-8728-ae76cc5c9dba.png)

**Comment by avihaycloudinary** [comment]
reproduce:
open free style job, add the following script
```bash
#!/bin/bash
set -x
for i in {1..5000}; do  
echo -e '\033[42m\033[97mWhite letters, green background\033[0m'
done
```

result:
- console screen
![image](https://user-images.githubusercontent.com/73224983/103396334-46541000-4b3b-11eb-9c4f-ec4983c67037.png)

- consoleFull screen
![image](https://user-images.githubusercontent.com/73224983/103396363-7dc2bc80-4b3b-11eb-8a03-e6d197262d21.png)

**Comment by tszmytka** [comment]
Thanks for the more accurate example. 
I am able to reproduce this with Jenkins `2.263`. It used to work correctly with `2.204` (all with `ansicolor 0.7.3`) so log handling must have changed in Jenkins in the mean time.

**Comment by tszmytka** [comment]
Last Jenkins version where this works correctly is `2.260`
