### ISSUE TITLE
env.TERM/TERM not set if global config is e.g. "xterm"

### ISSUE THREAD

**Issue by alexanderLinear** [jenkinsci/ansicolor-plugin#218]
i was running a declarative Pipeline on a Jenkins master with
a) the global configuration for ansicolor-plugin at '' value
b) the same with 'xterm' value
c) counter checking with some job local setting of ansiColor('xterm')

for case a) i found all to work as expected (env.TERM was null, sh "echo $TERM" returned 'dumb'; ansi color sequences were left as it is).
for case b) i found something not right: env.TERM was null, sh "echo $TERM" returned 'dumb'; but ansi color sequences were honored.
for case c) i round all to be as expected

### Test environment
```
- Jenkins Version: 2.235.5
- AnsiColor Version: 0.7.3
- Operating System running Jenkins: Linux Ubuntu 16.04
```

### Expected behavior
for case b) I expected the various levels of environment variable storage to be set on a global level

### Actual behavior
for case b) the environment variables were left at the defaults.

### Steps to reproduce the behavior
see inital paragraph

### Issue checklist
- [x] Jenkins version
- [x] AnsiColor version
- [x] Operating System name and version
- [x] Expected behavior
- [x] Actual behavior
- [x] Steps to reproduce the behavior

**Comment by tszmytka** [comment]
Thanks for reporting. 
I can understand that this is annoying but what is the actual harm in not getting the correct name in the `TERM` env var (if - as you mention - the sequences are interpreted correctly)?

Would you also be able to post your pipeline? I can reproduce this but want to make sure we're talking about the same thing.

**Comment by alexanderLinear** [comment]
(sorry, did not notice the updates here until now)

> I can understand that this is annoying but what is the actual harm in not getting the correct name in the `TERM` env var (if - as you mention - the sequences are interpreted correctly)?

some of the pipline codes (shared library) are forcefully applying ansi colors as a clamp wrapper and thus resulting in extra prints in the log.
for decreasing that i tested on already present features so to avoid applying those extra step without need.
when the environment was lacking that value then detection would not work as it sould have.

> Would you also be able to post your pipeline? I can reproduce this but want to make sure we're talking about the same thing.

its too big and also not in a public space nor do i feel eliged to that. extracting relevant codes in a run-able subset would be noticeable effort - too much for now for the trivia of the issue i think. i am sorry for not being able.

**Comment by eightnoneone** [comment]
My use-case was that the ansible plugin requires a param of `colorized: true` when calling `ansiblePlaybook()`. 

I was hoping to test `env.TERM` and set the param accordingly. I'm running 1.0.2 and this is not working if set as server global. Value for `env.TERM` is null.  I'll try to come up with a succinct example script.

```
ansiblePlaybook(
                        playbook: "site.yml",
                        inventory: "${env.INVENTORY}",
                        credentialsId: 'some-ssh-key',
                        colorized: (env.TERM))
```
