### ISSUE TITLE
Ability to change font type

### ISSUE THREAD

**Issue by roman-khazanskii** [jenkinsci/ansicolor-plugin#221]
### Feature Request

It would be nice to have ability to change a font (or at least font family) to be used in Jenkins Output. Right now (for me, at least) font is not monospaced and it looks very strange; test output is not properly aligned.

**Comment by tszmytka** [comment]
I understand where you're coming from but the decision which font to use for a functionality (rendering console-like data) that is used by other parts of a fairly complicated system (Jenkins) is rather outside of the scope of `anisicolor-plugin`.
Have you tried [using themes](https://www.jenkins.io/doc/book/managing/ui-themes/)?

**Comment by roman-khazanskii** [comment]
Fair enough. I think there is something wrong with my setup because I'm already using a theme (with monospaced font for output) and ansicolor suddenly stopped working at all.
I guess this can be closed :) Thanks for you time!
