### ISSUE TITLE
freeStyleJob wrappers colorizeOutput(colorMap ='xterm') is not working 

### ISSUE THREAD

**Issue by amalcp** [jenkinsci/ansicolor-plugin#228]
I have a simple freeStyleJob DSL file to generate a basic job. 

Except for the colorizeOutput wrapper, all other options is enabled while the job is created from the seed job. 
Any guess why it is not enabling the "Color ANSI Console Output" option with this?
Jenkins Version: 2.263.1

>  freeStyleJob('devops/colorizeOutput') {
    description 'Test Firebase'
    logRotator(numToKeep = 50)
    label('jenkins-slave-test')
    wrappers {
        timestamps()
        `colorizeOutput(colorMap ='xterm')`
        preBuildCleanup()
        credentialsBinding {
          string('GITHUB_TOKEN','GITHUB_TOKEN')
        }
    }
    parameters {
        gitParameterDefinition {
            name('git_branch')
            type('PT_BRANCH_TAG')
            defaultValue('origin/develop')
            description('git parameter build')
            branch('*')
            branchFilter('')
            tagFilter('')
            sortMode('DESCENDING_SMART')
            selectedValue('NONE')
            useRepository('test-repo')
            quickFilterEnabled(true)
        }
        choiceParam('build_type', ['Debug', 'Release'])
    }
    steps {
        shell(readFileFromWorkspace('jenkins-dsl/scripts/android.sh'))
    }
}`

Seedjob will create this job without colorizeOutput and I can edit it manually and see the expected output.

**Comment by tszmytka** [comment]
What is the bug in `ansicolor-plugin` then?

>Seedjob will create this job without colorizeOutput

If it doesn't get enabled in your job then why would you expect it should work?
Seems like a problem either with your job script or `job-dsl-plugin`.
If the output is colorized after manually setting the `Color ANSI Console Output` option then `ansicolor-plugin` is working fine.
