### ISSUE TITLE
Ansi colors not seen while the console output is in progress

### ISSUE THREAD

**Issue by manosnoam** [jenkinsci/ansicolor-plugin#229]
New issue originate from:
https://github.com/jenkinsci/ansicolor-plugin/issues/216#issuecomment-841871255

In freestyle job, AnsiColors are not seen while the console output is **still in progress**, for example:
`[33mThis should be yellow text[0m`

![image](https://user-images.githubusercontent.com/9913945/119619456-b033c580-be0c-11eb-968e-96c29b2fc16f.png)

Notes:
1) If going to `/consoleFull` page - Then Ansi colors are shown correctly.
2) Once the build completes, refreshing the `/console` page also shows Ansi colors correctly:

![image](https://user-images.githubusercontent.com/9913945/119619410-a14d1300-be0c-11eb-814f-cb841c9523f9.png)

### Version report

AnsiColor plugin version 0.7.5 on Jenkins 2.277.2

**Comment by tszmytka** [comment]
Would you be able to provide a long-running pipeline for reproducibility?

**Comment by tszmytka** [comment]
>freestyle, with multiple shell steps.

That would work as well.

**Comment by kugel-** [comment]
Isn't this the same as #216 ?
