### ISSUE TITLE
Plugins page on jenkins.io appears newer than GitHub

### ISSUE THREAD

**Issue by dmillar-vx** [jenkinsci/ansicolor-plugin#257]
### Describe your use-case which is not covered by existing documentation.

The [Jenkins.IO](https://plugins.jenkins.io/ansicolor/) page lists the newest version as 1.0.2, whereas currently the newest release on GitHub is 1.0.1. The 1.0.2 release listed on Jenkins.IO does not list what changes have been made since 1.0.1 and the lack of matching here makes the 1.0.2 release on Jenkins.IO seem suspect. Can a maintainer please clarify if it was a real release or check into the validity of it?

**Comment by dblock** [comment]
When releasing 1.0.2 I followed https://github.com/jenkinsci/ansicolor-plugin/blob/master/RELEASING.md. Is something missing there? Did something change that failed to make a GitHub release. Frankly the maven/jenkins release plugins are mystery meat to me.

**Comment by dblock** [comment]
Maybe @tszmytka knows?

**Comment by tszmytka** [comment]
The repository is configured to automatically generate Github release drafts but the final confirmation step needs to be done by a live person. 
@dblock You need to go to [releases](https://github.com/jenkinsci/ansicolor-plugin/releases), edit the newest draft, give it the same version number as maven did and publish it.

**Comment by tszmytka** [comment]
> @tszmytka Care to do it?

OK. You authored the release so I didn't want to steal that pleasure away. 😉 

I just documented the `1.0.2` release in GitHub.

**Comment by dblock** [comment]
Can you help edit https://github.com/jenkinsci/ansicolor-plugin/blob/master/RELEASING.md as well with the instructions of what to do? I missed it because I didn't know 😅
