### ISSUE TITLE
Use HTML output in email

### ISSUE THREAD

**Issue by jacobweber** [jenkinsci/ansicolor-plugin#29]
Is it possible to configure this plugin to work with the [Email-Ext plugin](https://wiki.jenkins-ci.org/display/JENKINS/Email-ext+plugin), so that we could send HTML emails with colorized log output?

**Comment by kaystrobach** [comment]
as i use jenkins for behat tests, I would prefer coloured mails as well. :+1:

**Comment by kaystrobach** [comment]
just took a look into the docs, seems to be possible atleast:

https://wiki.jenkins-ci.org/display/JENKINS/Email-ext+plugin

```
Pre-send Script
The pre-send script is a feature which allows you to write a script that can modify the MimeMessage object prior to sending. This would allow adding custom headers, modifying the body, etc. Predefined variables include:

msg - the MimeMessage object which can be modified
logger - a PrintStream and will write to the job's log. 
build - the build this message belongs to
cancel - a boolean, which when set to true will cancel the sending of the email
```

**Comment by kaystrobach** [comment]
but i would prefer to have this with the default jenkins mail plugin ...

**Comment by emoxam** [comment]
8 years and no news ?
