### ISSUE TITLE
Pieces of base-64 garbled output display in partial views 

### ISSUE THREAD

**Issue by dblock** [jenkinsci/ansicolor-plugin#30]
Partial truncated text.

![screenshot 2014-05-30 07 30 22](https://cloud.githubusercontent.com/assets/542335/3129935/cd998cc4-e7ed-11e3-8c4b-ac781af5b450.png)

![screenshot 2014-05-30 07 29 53](https://cloud.githubusercontent.com/assets/542335/3129933/bd3e544a-e7ed-11e3-990f-9d9df992a7a3.png)

**Comment by MartinNowak** [comment]
Yes, this is simply a side-effect of #67. The base64 encoded data can't be interpreted to sth. sensible when picked up mid-stream (due to not showing the full log).

**Comment by tszmytka** [comment]
Having spent a fair amount of time with #185 I can say something about this. 

This issue has nothing to do with `ansicolor` directly. Jenkins produces the partial views simply by taking the last `x` bytes from the log - currently it is `150 KB` - without looking if it happens to fall in the middle of an encoded `ConsoleNote` or not.
Any other plugin or internal Jenkins functionality that uses `ConsoleNote`s will exhibit the same behavior.

@dblock I think this can be closed as any attempts at fixing this would require **manually updating** the log file - I actually went in that direction at the beginning of #198

**Comment by dblock** [comment]
I think this can stay open since it's still an issue. I agree there's nothing sensible AnsiColor can do right now, but maybe someone encountering this problem will have a better idea (e.g. improving how Jenkins reads log tails).

**Comment by tszmytka** [comment]
@dblock I've fixed this behavior directly in Jenkins some time ago already (as the ticket above shows) and forgot to post an update. Jenkins version `2.261` (or newer) will always render partial logs starting from the beginning of a line - `ConsoleNote`s (parts of them) will no longer show up in the output no matter what.
