### ISSUE TITLE
AnsiColor not working

### ISSUE THREAD

**Issue by ItachiSan** [jenkinsci/ansicolor-plugin#33]
Hello,
I've problems while running colored output, as it is not colored.
I don't really get where the problem is; I don't get if it's a personal problem or not.

The actual setup:
- Jenkins 1.554.3
- Ubuntu Server 12.04
- AnsiColor plugin 0.4.0
- Snippet of code:
  `echo -e "\e[31mRed Text\e[0m"
  echo -e "\e[42mGreen Background\e[0m"`

**Comment by p00j4** [comment]
I have **jest javascript** tests writing to the console and only for these tests none of the colour coding is working though the same works on any normal shell/zsh terminal. 
I tried to add export for `dash` fix just for exporation at the begging of the job run but that didn't help. 
1. Do I need different  declares
2. Do I need to build the plugin locally with the declares (if exporting withing the job doesn't help as plugin is already loaded before that)

Have tried to understand the codes by saving logs into file but didn't find any meaningful codes in there.
```
 RUNS  ...segment.reducer.spec.js
^M^[[K^M^[[1A^M^[[K^M^[[1A
 RUNS  ...displaySettings.store.parser.spec.js
^M^[[K^M^[[1A^M^[[K^M^[[1A
 RUNS  ...displaySettings.store.parser.spec.js
^M^[[K^M^[[1A^M^[[K^M^[[1A
```
