### ISSUE TITLE
Promoting Status Console Output

### ISSUE THREAD

**Issue by juanitogan** [jenkinsci/ansicolor-plugin#34]
Probably a change needed on the Promoted Builds plugin rather than this plugin (unless you can solve the global setting trick) but I noticed that the console output from promotions don't respond to ANSI codes.  Promotions are where I currently do my Ruby bundling and such (with Ruby, I can put the whole pipeline inside a single project -- still testing if it is a good idea or not to do this).

Just something to think about and test if you ever find a way to intercept console output at a lower level.

**Comment by beeerd** [comment]
+1, also unclear to me whether this is a problem with ansicolor or promoted builds plugin.

**Comment by alisade** [comment]
+1

**Comment by tszmytka** [comment]
Apparently this got implemented in `promoted-builds-plugin` and fixed with https://github.com/jenkinsci/promoted-builds-plugin/pull/99
