### ISSUE TITLE
Allow color maps to specify BOLD attributing switching to high intensity instead of bold type face

### ISSUE THREAD

**Issue by ejelly** [jenkinsci/ansicolor-plugin#43]
Some terminals, like VGA, do not actually have a bold typeface but switch to the high intensity color map instead. We should support that.

**Comment by pegrau** [comment]
Hello,

I understand that you don't want the tag b for the bold typeface.

What HTML resource you suggest to use to translate the bold type?

**Comment by Joe-Merten** [comment]
As I understand, he wants an option to e.g. behave `esc[33;1m` like `esc[93m` appears.

**Comment by jahudgins** [comment]
Yes. This is important for a project I am working on. The output from jest tests coverage is output in bold. `esc[32;1m` instead of `esc[32m` which indicates bold.

**Comment by JoeMerten** [comment]
Just for a note:

For my understanding, terminal emulators are free to choice if they interpret `esc[1m` for bold type or bright color (see also https://en.wikipedia.org/wiki/ANSI_escape_code).

I'd checked some interpreters (see also https://github.com/JoeMerten/Jfe/blob/master/Framework/tools/AnsiColors.py) and found out that frontends which have black background (e.g. Kubuntu Konsole) tend to choose bright color, as were frontends which have white background rather using bold typeface instead.

For my opinion this is good behavior, as e.g. bright red looses contrast at white background but normal red with bold typeface got more attention. But on black background, the bright red is the better choice to earn more attention.

However, some frontends can be configured to apply either bright color or bold typeface for `esc[1m` (e.g. Kubuntu Konsole, Eclipse Ansi Console, …).

I think that it's not a big thing to implement the alternative behavior. But we need a suggestion how to configure this.

- Maybe adding a checkbox to the custom color map configuration (option for each color map).
- Or adding a checkbox to the jenkins job configuration.

What's your suggestion about this?

**Comment by jahudgins** [comment]
Either bold or bright would be ok. But it should still be the specified color. Right now ansi color on `esc[32;1m` displays bright (or maybe bold not sure) white. But it should be green (32) -- I don't think there needs to be an option for bold or bright.

**Comment by JoeMerten** [comment]
Just tried out with AnsiColor 0.5.0, it looks ok `esc[32;1m` displays bold green:

![ansicolors](https://user-images.githubusercontent.com/6552470/34610523-d0fc574c-f221-11e7-8e87-0dd04a0f3b29.png)

Please run [AnsiColors.py](https://github.com/JoeMerten/Jfe/blob/master/Framework/tools/AnsiColors.py) on your Jenkins and post the result as a screenshot. We maybe have an issue with the current 0.5.2 about this which I have not tested until now.
