### ISSUE TITLE
Output from Colorize Ruby gem doesn't appear colorized

### ISSUE THREAD

**Issue by toddmazierski** [jenkinsci/ansicolor-plugin#5]
Colored console output from the [Colorize Ruby gem](https://github.com/fazibear/colorize) doesn't appear colorized in the Jenkins console.

In addition to the color code, the gem includes the mode and background color. Are these not supported?

``` RUBY
"\033[#{color_parameters[:mode]};#{color_parameters[:color]+30};#{color_parameters[:background]+40}m#{color_parameters[:uncolorized]}\033[0m".set_color_parameters( color_parameters )
```

Thanks!

**Comment by dothebart** [comment]
according to http://stackoverflow.com/questions/1401002/trick-an-application-into-thinking-its-stdin-is-interactive-not-a-pipe
the 'script'  command can solve this for you. Imho it should be somewhere prominent on the howto ;-)

**Comment by dblock** [comment]
@dothebart Please contribute to the doc.
