### ISSUE TITLE
Pipeline (formerly Workflow) snippet generator unhelpful

### ISSUE THREAD

**Issue by leth** [jenkinsci/ansicolor-plugin#65]
The snippet generator for wrap -> Color ANSI Console output gives a pretty unhelpful snippet:

```
wrap(<object of type hudson.plugins.ansicolor.AnsiColorBuildWrapper>) {
    // some block
}
```

The only place I found out how to use it was from your README.md :)

**Comment by dblock** [comment]
What do you suggest @leth? Please contribute!

**Comment by qvicksilver** [comment]
We could use the same example as in README.md?

**Comment by leth** [comment]
I think the idea of the snippet generator is it has all the same controls as the classic UI, and then compiles that into text for you. That's what the other options seem to do anyway

On 23 January 2016 15:53:23 GMT+00:00, qvicksilver <notifications@github.com> wrote:
>We could use the same example as in README.md?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/dblock/jenkins-ansicolor-plugin/issues/65#issuecomment-174195733

-- 
Sent from my phone. Please excuse my brevity.

**Comment by leth** [comment]
I haven't the slightest clue how to set up a Dev stack for any of this Jenkins stuff :P

On 23 January 2016 15:33:42 GMT+00:00, "Daniel Doubrovkine (dB.) @dblockdotorg" <notifications@github.com> wrote:
>What do you suggest @leth? Please contribute!
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/dblock/jenkins-ansicolor-plugin/issues/65#issuecomment-174194050

-- 
Sent from my phone. Please excuse my brevity.

**Comment by qvicksilver** [comment]
Got some time to play with this. Just removing the unused integers from the constructor parameters (defaultFg and defaultBg) produces a nicer snippet.

```java
    @DataBoundConstructor
    public AnsiColorBuildWrapper(String colorMapName, Integer defaultFg, Integer defaultBg) {
        this.colorMapName = colorMapName;
    }
```

```groovy
wrap([$class: 'AnsiColorBuildWrapper', colorMapName: 'xterm']) {
    // some block
}
```

I can't see those being used anywhere else in the code so I guess they should be safe to remove?

**Comment by dblock** [comment]
Yes!

**Comment by qvicksilver** [comment]
https://github.com/dblock/jenkins-ansicolor-plugin/pull/66

**Comment by davey-dev** [comment]
Works but how do I modify the xterm colorMap??

**Comment by OwnerOfThisIsle** [comment]
It would be really helpful, to state how to use this "wrap" in declarative Syntax.

Well - if it is possible at all.

**Comment by JoeMerten** [comment]
Just tried out with AnsiColor 0.5.0 and the snippet generator shows me:

    ansiColor('xterm') {
        // some block
    }

I think, there is nothing more to di, isn't it?

**Comment by ericfrancis** [comment]
Would be nice to see some common examples. 

Where does the ansiColor configuration go in a declarative Jenkinsfile?

```
pipeline {
  agent any

  // Set log rotation, timeout and timestamps in the console
  options {
    buildDiscarder(logRotator(numToKeepStr:'10'))
    timeout(time: 5, unit: 'MINUTES')
  }

  stages {

    stage('Initialize') {
      steps {
        sh '''
          java -version
          node --version
          npm --version
        '''
      }
    }
```

**Comment by medianick** [comment]
@ericfrancis, in a Declarative Pipeline it looks like this:

```
pipeline {
  agent any

  options {
    ansiColor('xterm')
    buildDiscarder(logRotator(numToKeepStr:'10'))
    timeout(time: 5, unit: 'MINUTES')
  }

// ... additional steps 
```

**Comment by tszmytka** [comment]
It seems that all questions have been answered. The [README](https://github.com/jenkinsci/ansicolor-plugin/blob/master/README.md) shows multiple examples of how configure the plugin.
