### ISSUE TITLE
java.lang.NoClassDefFoundError: jenkins/tasks/SimpleBuildWrapper

### ISSUE THREAD

**Issue by ender672** [jenkinsci/ansicolor-plugin#68]
ansicolor plugin version 1.4.2 breaks on jenkins version 1.545 with the following error:

```
Mar 9, 2016 9:51:10 AM hudson.plugins.ansicolor.PluginImpl start
INFO: AnsiColor: eliminating boring output (https://github.com/dblock/jenkins-ansicolor-plugin)
Mar 9, 2016 9:51:10 AM jenkins.InitReactorRunner$1 onAttained
INFO: Prepared all plugins
Mar 9, 2016 9:51:16 AM hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1 error
WARNING: Failed to instantiate Key[type=hudson.plugins.ansicolor.AnsiColorBuildWrapper$DescriptorImpl, annotation=[none]]; ski
pping this component
com.google.inject.ProvisionException: Guice provision errors:

1) Error injecting constructor, java.lang.NoClassDefFoundError: jenkins/tasks/SimpleBuildWrapper
  at hudson.plugins.ansicolor.AnsiColorBuildWrapper$DescriptorImpl.<init>(Unknown Source)

1 error
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:52)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1.get(ExtensionFinder.java:429)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:1005)
```

Downgrading to version 1.4.1 works.

**Comment by b-dean** [comment]
Looks like you need something like this in your `pom.xml`

```xml
<properties>
    <jenkins.version>1.599</jenkins.version>
</properties>
```

**Comment by dblock** [comment]
@b-dean I think the whole issue is that it doesn't work for jenkins 1.545, are you saying we need to lock the version to something higher? PR?

**Comment by b-dean** [comment]
The original comment on the commit said
> I think there's some way to tell Jenkins that this version requires jenkins version X

I'm just mentioning what that is. I'm using Jenkins 2.20 so this issue doesn't really affect me. But if someone else wants to take the time to figure it out and make a PR, maybe that `<jenkins.version>` would help.

**Comment by JackMetkus** [comment]
Well I am running version 2.15 and I have the same issue.  So, it is not just related to the version.

**Comment by JackMetkus** [comment]
It would be good to know  where this class is supposed to installed

**Comment by JoeMerten** [comment]
I'd recently done some tests against jenkins 1.653, 2.32.3, 2.49 and 2.50 and have not seen those exceptions until now. Could you provide simple steps how to reproduce, e.g. like:
- fresh installed jenkins <version>
- installed AnsiColor <version> plugin
- exception during plugin installation and / or next jenkins start and / or build job execution

Could you test against AnsiColor 0.5.1-SNAPSHOT? 
→ Maybe it's also related to https://github.com/jenkinsci/ansicolor-plugin/issues/101#ref-commit-057db6c

**Comment by tszmytka** [comment]
The plugin currently requires Jenkins `2.176.3` or higher. No similar errors reported for over 3 years. 
I think it is reasonable to assume the bug (if there was any) has been fixed "along the way".
