### ISSUE TITLE
Is there a way to make the XTerm background black?

### ISSUE THREAD

**Issue by jaytaylor** [jenkinsci/ansicolor-plugin#69]
First off- This jenkins plugin is fantastic!  Thank you @dblock and all other contributors!

Is there a way to get use the XTerm theme except with a black background on white text?

Thanks again!

**Comment by dblock** [comment]
Did you try a custom color map? 

![](https://github.com/dblock/jenkins-ansicolor-plugin/raw/master/images/ansicolor-config.png)

**Comment by jaytaylor** [comment]
I didn't know that was an option... I will give it a try.

Thank you!

**Comment by dblock** [comment]
Reopen if that doesn't help.

**Comment by jaytaylor** [comment]
Whoops, guess that was a little premature and I don't think I have permission to re-open.

So I found the config section and changed it like so (reversed BG/FG colors and changed "Black" to #BBBBBB):

![screen shot 2016-03-16 at 2 29 36 pm](https://cloud.githubusercontent.com/assets/435652/13829325/a6296a06-eb83-11e5-91ac-8a9e5b64760c.png)

And I've restarted the Jenkins service and re-run the task but the black background color isn't happening:

![screen shot 2016-03-16 at 2 31 14 pm](https://cloud.githubusercontent.com/assets/435652/13829363/dd407aac-eb83-11e5-9f0e-ac7f93ea7ee9.png)

**Comment by jaytaylor** [comment]
wrap([$class: 'AnsiColorBuildWrapper', 'colorMapName': 'xterm']) {
        ...
    }

So after changing the task to use lowercase "xterm" instead of "XTerm", I now have some gray background (see screenshot below), but still no black background.  Are the color scheme names supposed to be case-sensitive? If so, then why are all the names in lowercase in the web config?

![screen shot 2016-03-16 at 2 38 23 pm](https://cloud.githubusercontent.com/assets/435652/13829560/dcea626a-eb84-11e5-9a0d-41f9264b6de8.png)

**Comment by dcendents** [comment]
The Jenkins material theme sets a dark background for the console: http://afonsof.com/jenkins-material-theme/

**Comment by tszmytka** [comment]
I guess the author figured this out on his own but there must have been something else interfering with the settings,

Using the exact steps from https://github.com/jenkinsci/ansicolor-plugin/issues/69#issuecomment-197557735 in `ansicolor v0.7.2` produces `xterm` style output with black background and white foreground.
