### ISSUE TITLE
no color scheme for white background

### ISSUE THREAD

**Issue by ssbarnea** [jenkinsci/ansicolor-plugin#77]
White backgrounds to fit better for web pages (including Jenkins) but it seems that the 4 default color schemes of AnsiColor are all on dark backgrounds. 

Also I find them confusing because you never know what to pick and once you picked one your executed job will keep its scheme.

I find most of the schemes as low-contrast, but so far `vga` one provided the best contrast. TO be hones trying to read an ansible error (red) on the default dark gray background of the xterm scheme hurts your eyes. 

I may be biased but I would prefer to have the schemes configured only in jenkins main configuration and allowing us to tune them without having to re-run the jobs.

**Comment by dblock** [comment]
The plugin modifies log output as the job runs, at least currently there's no way to go back to that output and re-apply a color scheme.

**Comment by ssbarnea** [comment]
There is! Instead of using css colors just use class names for each color. Changing the theme would be a matter of having a different css.

Btw, editing the default schemes is really weird as if you rename one it will create a copy and not remove the original one.

**Comment by dblock** [comment]
That sounds great as long as there's a way to inject CSS or the theme name later. Feel free to contribute :)
