### ISSUE TITLE
Chinese can not display all the information

### ISSUE THREAD

**Issue by dcl-lily** [jenkinsci/ansicolor-plugin#78]
Chinese can not display all the information
Hi
   I use the python script, the output of Chinese, in the shell display normal
python code：
`
print '\e[31m 技术部-运维台帐管理系统 \e[0m\n'
.......................
`

Hudson display ：

[workspace] $ /bin/sh -xe /tmp/hudson2372612837150118721.sh
- cd /opt/hudson/check
- ./a10_ssh_check.py A10_A
  `<span style="color: green;"> 磁盘状态正常 ,�</span><span style="display: none;">[32m 磁盘状态正常 ,目前使用率:23.7%
  </span>
  <span style="display: none;">[0m
  </span><span style="color: green;"> 服务状�</span><span style="display: none;">[32m 服务状态运行正常 
  </span>
  <span style="display: none;">[0m
  </span><span style="color: green;"> 内存状态正常,�</span><span style="display: none;">[32m 内存状态正常,使用率为:55.7% 
  </span>
  <span style="display: none;">[0m
  </span><span style="color: green;"> Cpu状态正常,一�</span><span style="display: none;">[32m Cpu状态正常,一分钟平均值:1% 
  </span>
  <span style="display: none;">[0m
  </span>★★★★★<span style="display: none;">★★★★★★警告★★★★★
  </span>
  <span style="color: red;"> 主机节点有</span><span style="display: none;">[31m 主机节点有SLB服务宕机 
  </span>`

**Comment by dblock** [comment]
And the English example works?

**Comment by dcl-lily** [comment]
English output is normal, python script code is UTF-8

**Comment by dblock** [comment]
I would try to write a spec for this next.

**Comment by JoeMerten** [comment]
Tried out using:

- Jenkins 1.653
- Ansicolor 0.4.3
- Python 2.7.12
- Python 3.5.2
- Host: Kubuntu 16.04

Testscripts (freestyle job, build step, execute shell):

Bash:

    #!/bin/bash
    echo -e 'Chinese: \e[31m技术部-运维台帐管理系统\e[m Finish'

Python 3:

    #!/usr/bin/env python3
    print('Chinese: \x1B[31m技术部-运维台帐管理系统\x1B[m Finish')

Python 2:

    #!/usr/bin/env python
    # coding: utf8
    print 'Chinese: \x1B[31m技术部-运维台帐管理系统\x1B[m Finish'

All of them gave output as expected, like:
    ![screenshot-chinese-issue-78](https://cloud.githubusercontent.com/assets/6552470/24074833/9e43fd70-0c10-11e7-8cc1-976266a011e0.png)

Could you please provide a small but complete script to reproduce the issue?

**Comment by dcl-lily** [comment]
Thinks
