### ISSUE TITLE
On dark background the links are unreadable

### ISSUE THREAD

**Issue by Sweetchuck** [jenkinsci/ansicolor-plugin#79]
In the console output the URIs turn into clickable links and they have the default HTML styling (blue, and purple for visited links) but very difficult to read them.
![image](https://cloud.githubusercontent.com/assets/591103/18627723/c1c0be56-7e5c-11e6-8c8c-fb3b5ab27d71.png)

It would be awesome to add configuration options to link colours as well.

**Comment by ssbarnea** [comment]
I would suggest that ansicolorer should convert the basic 16 ANSI colors to named css styles and use these, allowing the user to tune the display based using CSS. 

In your case I would just change the back to be pure black, ti should sort most of the contrast issue.

**Comment by JoeMerten** [comment]
Doesn't got `AnsiColorMap CSS` a bit in this direction? But this map uses only 8 colors:

    public static final AnsiColorMap CSS = new AnsiColorMap(
            "css",
            "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white",
            "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white",
            null,
            null
    );

Further, we might think about using use more web originated color names:

    "black", "maroon", "green", "olive",  "navy", "purple",  "teal", "silver",
    "gray",  "red",    "lime",  "yellow", "blue", "fuchsia", "aqua", "white"

Or alternatively when using the names mentioned in [Wikipedia ANSI_escape_code](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors), something like this(?):

    "Black",    "Red",       "Green",       "Brown",  "Blue",       "Magenta",       "Cyan",       "Gray",
    "Darkgray", "BrightRed", "BrightGreen", "Yellow", "BrightBlue", "BrightMagenta", "BrightCyan", "White"

**Comment by Sweetchuck** [comment]
@JoeMerten I can create as many _color map_ with custom color codes as many I wish.
The problem is that I have no control over the link colors.

**Comment by JoeMerten** [comment]
Ok, I tried out with that bash script:

    #!/bin/bash
    echo -e "\e[31mMaroon\e[m"
    echo "http://www.jme.de"
    echo -e "\e[92mLime\e[m"

and it results to xterm:
<kbd>![colored-links-xterm](https://cloud.githubusercontent.com/assets/6552470/24290866/f49a8386-1086-11e7-8c0b-af8718ece318.png)</kbd>
css:
<kbd>![colored-links-css](https://cloud.githubusercontent.com/assets/6552470/24290876/facb7a4e-1086-11e7-9972-bf5070bffacb.png)</kbd>
vga:
<kbd>![colored-links-vga](https://cloud.githubusercontent.com/assets/6552470/24290879/fe07398c-1086-11e7-9ec4-0b20dc90b3e0.png)</kbd>
gnome-terminal:
<kbd>![colored-links-gnome](https://cloud.githubusercontent.com/assets/6552470/24290881/00632a38-1087-11e7-8182-6a76eaf0a482.png)</kbd>

In `AnsiColorMap` we already support optional specification of default foreground and background color, which currently both used by the both dark color schemes (vga and gnome-terminal).
We might add 4 optional entries for link coloring here (normal link, visited, hover, active).
Injecting them into the colored console html output isn't a big thing. But I'm not sure about compatibility against existing customized color maps.

**Comment by JoeMerten** [comment]
If we consider to try this approach, what colors would you suggest for the dark schemes?
