### ISSUE TITLE
Support coloring of labels of pipeline's "parallel" command

### ISSUE THREAD

**Issue by Bagira80** [jenkinsci/ansicolor-plugin#82]
I tried to colorize the label-output of Pipeline's `parallel` command.

    def taskName = "\u001B[31mLabel in red\u001B[0m";
    def task = { echo "\u001B[34mBody in blue\u001B[0m"; }
    parallel( "${taskName}", task );

However, it seems the label is just printed verbatim. Only the body is printed in color.
The output looks like this (with `Body in blue` in blue color).

    [[31mLabel in red[0m] Body in blue

Please forgive me, if this issue should be raised against Pipeline and its `parallel` command. However, maybe it is enough to adjust your plugin so that it supports that feature.

**Comment by dblock** [comment]
Seems like a legit feature request.

**Comment by dblock** [comment]
Does https://github.com/dblock/jenkins-ansicolor-plugin/pull/83 help with this?

**Comment by cpoenisch** [comment]
Sorry, #83 will not solve this request, because label output of `parallel` is interpreted as plain text here.

**Comment by Bagira80** [comment]
Sadly, I can confirm that even with #83 the label output of `parallel` is interpreted as plain text.
I guess, the internals of `parallel` must be changed to support coloring?

**Comment by JoeMerten** [comment]
Tried out the above mentioned example on Jenkins 2.32.3:

    def taskName = "\u001B[31mLabel in red\u001B[0m";
    def task = { echo "\u001B[34mBody in blue\u001B[0m"; }
    parallel( "${taskName}", task );

but got an exception:

    java.lang.IllegalArgumentException: Expected named arguments but got [[31mLabel in red[0m, org.jenkinsci.plugins.workflow.cps.CpsClosure2@efe9b4e]

@Bagira80, could you please make your example complete and running?
I also miss something like a `ansiColor('xterm') { … }`.

**Comment by JoeMerten** [comment]
I'd never worked with `parallel` until now, but tried to create an example based on https://github.com/jenkinsci/pipeline-examples/blob/master/pipeline-examples/parallel-from-list/parallelFromList.groovy.
Unfortunetely, my example is definitively not minimal:

    ansiColor('xterm') {
        // Our initial list of strings we want to echo in parallel
        def stringsToEcho = ["a", "b", "c", "d"]
        // The map we'll store the parallel steps in before executing them.
        def stepsForParallel = [:]
        for (int i = 0; i < stringsToEcho.size(); i++) {
            // Get the actual string here.
            def s = stringsToEcho.get(i)
            def color = "${i+31}"
            // Transform that into a step and add the step to the map as the value, with a name for the parallel step as the key. Here, we'll just use something like "echoing (string)"
            def stepName = "echoing \u001B[${color}mCOLOR\u001B[m ${s}"
            stepsForParallel[stepName] = transformIntoStep(s + "\u001B[${color}mCOLOR\u001B[m")
        }
        // Actually run the steps in parallel - parallel takes a map as an argument, hence the above.
        parallel stepsForParallel
    } // ansiColor

    // Take the string and echo it.
    def transformIntoStep(inputString) {
        // We need to wrap what we return in a Groovy closure, or else it's invoked when this method is called, not when we pass it to parallel.
        // To do this, you need to wrap the code below in { }, and either return that explicitly, or use { -> } syntax.
        return {
            node {
                echo inputString
            }
        }
    }

And the result is:
<kbd>![ansicolor-parallel](https://cloud.githubusercontent.com/assets/6552470/24260616/d858af14-0ff4-11e7-8a4e-b51611e44ac0.png)</kbd>

Finally the same conclusion as found out by Bygira80: "… the label is just printed verbatim. Only the body is printed in color."

It might be related to #104.

**Comment by herter4171** [comment]
Hello, I would like this feature.  Color renders properly during the initial run, but color often doesn't persist when the page is reopened.  In my pipeline, I have `ansiColor` set to `xterm` in the options block and around steps that will print in color, but color is still dropped in parallel stages after a reload.

Original page showing colors like it should:
![image](https://user-images.githubusercontent.com/21989132/122100485-19817580-cdc8-11eb-8fc7-ac580de01002.png)

Portion of the exact same log after loading in a new tab:
![image](https://user-images.githubusercontent.com/21989132/122100593-328a2680-cdc8-11eb-8d1f-21b19855aca4.png)
