### ISSUE TITLE
Access to original build log or export current as HTML

### ISSUE THREAD

**Issue by UksusoFF** [jenkinsci/ansicolor-plugin#84]
Before this plugin we get log from `/var/lib/jenkins/jobs/${JOB_NAME}/builds/${BUILD_ID}/log`
Now it's contains many not readable data:
`ha:AAAApR+LCAAAAAAAAP9b85aBtbiIQT2jNKU4P0+vIKc0PTOvWC8xrzgzOT8nv0gvODO3ICfVoyQ3xy+/JNU2Yj/Tagmf50wMjD4M7CWJ6SCJEgYhn6zEskT9nMS8dP3gkqLMvHTriiIGKaihyfl5xfk5qXrOEBpkDgMEMDIxMFQUlDDI2RQXJOYpFJdU5qTaKoEttlJQNjBwdjEwsFayAwAsE8VZpQAAAA==ha:AAAAjR+LCAAAAAAAAP9b85aBtbiIQT2jNKU4P0+vIKc0PTOvWC8xrzgzOT8nv0gvODO3ICfVoyQ3xy+/JNU2Yj/Tagmf50wMjD4M7CWJ6SCJEgYhn6zEskT9nMS8dP3gkqLMvHTriiIGKaihyfl5xfk5qXrOEBpkDgMEMDIxMFQUlDAw2yTZAQAIfTy0igAAAA==PASSha:AAAAjh+LCAAAAAAAAP9b85aBtbiIQT2jNKU4P0+vIKc0PTOvWC8xrzgzOT8nv0gvODO3ICfVoyQ3xy+/JNU2Yj/Tagmf50wMjD4M7CWJ6SCJEgYhn6zEskT9nMS8dP3gkqLMvHTriiIGKaihyfl5xfk5qXrOEBpkDgMEMDIxMFQUlDCw2Ogn2QEAspZgwYsAAAA=ha:AAAAkR+LCAAAAAAAAP9b85aBtbiIQT2jNKU4P0+vIKc0PTOvWC8xrzgzOT8nv0gvODO3ICfVoyQ3xy+/JNU2Yj/Tagmf50wMjD4M7CWJ6SCJEgYhn6zEskT9nMS8dP3gkqLMvHTriiIGKaihyfl5xfk5qXrOEBpkDgMEMDIxMFQUlDCw2+gXFyTm2QEAI9P8iI4AAAA= `
Is there a way to make readable html? Or trim this for simple text log?

**Comment by UksusoFF** [comment]
This is a [bug](https://issues.jenkins-ci.org/browse/JENKINS-11752)?

**Comment by UksusoFF** [comment]
#15
#23

**Comment by dblock** [comment]
Is this https://github.com/dblock/jenkins-ansicolor-plugin/issues/30?

**Comment by UksusoFF** [comment]
It's probably related. But not duplicated.
#30 has garbage in Jenkins Console Output.
But this issue about garbage in  /var/lib/jenkins/jobs/devTourcatalog/builds/${BUILD_ID}/log

**Comment by tszmytka** [comment]
> Now it's contains many not readable data:

These are gzipped and Base64 encoded `ConsoleNote`s that are a standard Jenkins feature for adding meta-data to a log line. It is used by multiple other plugins including core Pipeline framework components.

There **was** a problem with older versions of `ansicolor` (pre `v0.6.0`) which used to heavily depend on them. Nowadays they are used as seldom as possible but getting rid of them entirely (without sacrificing a large part of functionality) is just not possible.

The logs produced by jobs are Jenkins internal data structures and were never meant to be read externally. If you really, really really need to access them then what may help is still getting them through Jenkins but without its UI - the `Blue Ocean` set of plugins access the logs in this exact way. Maybe take a look at [blueocean-rest](https://plugins.jenkins.io/blueocean-rest/).
