### ISSUE TITLE
Color plugin leads to endless cycle

### ISSUE THREAD

**Issue by orkenstein** [jenkinsci/ansicolor-plugin#85]
**ansicolor-0.4.3**
I have a `jenkinsfile`:
```
node('mac&&master') {
  ansiColor('xterm') {
    stage('Checkout') {
      gitClean()
      checkout scm
    }
    stage('Environment Setup') {
      sh '''
        brew unlink imagemagick
        brew install imagemagick
        brew link imagemagick
        gem install bundler
        cd Projects/FutureMobile
        bundle install --deployment
      '''
    }
    stage('Fastlane Build & Install') {
      sh '''
        ENGINE_PATH="/Users/App/~/sharedspace/UE_test/LocalBuilds/Engine/Mac/"
        cd Projects/FutureMobile
        VERSION=0.0.7
        export LANG=en_US.UTF-8
        echo $GIT_BRANCH
        echo $JOB_NAME
        bundle exec fastlane build_pr version:$VERSION build:$BUILD_NUMBER engine_path:$ENGINE_PATH
      '''
    }
  }
}
```
And  the colour plugin leads to endless loops at the stage. Console output looks like this (note date stamps):
```
[12:55:45]: ▸ 53 warnings generated.
[12:55:45]: ▸ [49/135] Compile EraStore.cpp
[12:55:45]: ▸ 49 warnings generated.
[12:55:45]: ▸ [50/135] Compile CustomWidgetStore.cpp
[12:55:13]: ▸ In file included from /Users/App/~/workspace/feature_New_engine_routines-B7HJHIXU7FTK2J3V47JVSAJGTN36OGKYX7FP6OXDAARYE6U3EQ7A/Projects/FutureMobile/Source/Infrastructure/Private/StartupManager.cpp:6:
[12:55:13]: ▸ In file included from ../../../../../../../workspace/feature_New_engine_routines-B7HJHIXU7FTK2J3V47JVSAJGTN36OGKYX7FP6OXDAARYE6U3EQ7A/Projects/FutureMobile/Source/I
```

Without `ansiColor`. It works just fine. The same for `wrap([$class: 'AnsiColorBuildWrapper', 'colorMapName': 'XTerm'])`.

**Comment by dblock** [comment]
Did you ever figure this out @orkenstein?

**Comment by orkenstein** [comment]
@dblock no. Had to switch to another gazillion Jenkins issues.

**Comment by wdvr** [comment]
I can confirm this issue. It doesn't always happen for me (30-40%), only with pipelines (color output for normal jobs works just fine).

**Comment by gronico** [comment]
Same here.
Only with pipelines.

**Comment by jakubjosef** [comment]
I created a pure JS version, because we really want to have colorised output.
Enjoy! https://github.com/jakubjosef/jenkins-ansi-color-js

**Comment by junpengl** [comment]
Encountered similar issue with Jenkins 2.73.2 and ansiColor plugin. That only happens for us when the log is really large (larger then 50MBs) and after we enable the ansiColor plugin on pipeline jobs. Seems related to Jenkins pipeline logging system. https://issues.jenkins-ci.org/browse/JENKINS-44483

**Comment by melezov** [comment]
This trashed our Jenkins server - endless stages and logs growing from 100MB to 1.1GB per build. Our champion was a log file of 30 GB because of this winning combination. It's also impossible to uninstall the ansiColor by just disabling it.

**Comment by tszmytka** [comment]
The symptoms seem to indicate (haven't managed to reproduce any of the examples in this thread in `v0.7.2`) another problem caused by generous `ConsoleNote` usage - `ansicolor` used to annotate each line of output with meta data which may have led to bloated log files.

Since `ansicolor v0.7.0` the annotations are used only to indicate begin/end of an `ansiColor()` area and as a shortlog trigger. As a result the logs should grow by a couple of `KB`s tops which allows even jobs producing hundreds of `MB`s of output to finish in a reasonable time.
