### ISSUE TITLE
Jenkins 2.32.2 compatibility

### ISSUE THREAD

**Issue by genei09** [jenkinsci/ansicolor-plugin#86]
After upgrading to 2.32.2 all historic output lost color.
After reverting to 2.32.1 all historic output has color again

**Comment by johnarnold** [comment]
https://jenkins.io/doc/upgrade-guide/2.32/#upgrading-to-jenkins-lts-2-32-2

Have you tried setting console to insecure?

**Comment by johnarnold** [comment]
Need to work out a way to support signed console notes...

**Comment by hacker112** [comment]
Running Jenkins 2.89.2 and adding the `-Dhudson.console.ConsoleNote.INSECURE=true` in the start script I still don't get any colour. I know that this has worked on my jenkins jobs before. Has anything more changed that I need to take in to consideration?

**Comment by George02** [comment]
I'm having the same issue while using Jenkins 2.128.

**Comment by tszmytka** [comment]
A lot has changed in `ansicolor-plugin` and this bug must have been fixed along with a different one.
There are no problems with opening logs for previously executed jobs after migrating between different Jenkins versions. Tested with:
- 2.222
- 2.260
- 2.273

Please open a new issue if you encounter similar issues.
