### ISSUE TITLE
Plugin does not work at all

### ISSUE THREAD

**Issue by dprinz** [jenkinsci/ansicolor-plugin#87]
I installed plugin version 0.4.3 on Jenkins ver. 1.580.3.

The option "Color ANSI console output" does not appear in any build. Is my Jenkins version too old?

**Comment by dblock** [comment]
If the plugin installed, it should work.

**Comment by dblock** [comment]
Did you ever figure this out @dprinz?

**Comment by dblock** [comment]
Closing.
