### ISSUE TITLE
Background isn't dynamic

### ISSUE THREAD

**Issue by landsman** [jenkinsci/ansicolor-plugin#88]
Hi,

what about change your plugin to changing background for main wrapper:
`<pre id="out" class="console-output">`

Because actually solution doesn't work good:
![snimek obrazovky 2017-02-23 v 18 58 21](https://cloud.githubusercontent.com/assets/3184228/23272096/3e527928-f9fa-11e6-9fa8-cdd8128a3cd0.png)

Is possible use javascript / css for it?

**Comment by dblock** [comment]
Open to suggestions, please make a PR.

**Comment by colinjcahill** [comment]
any update on this?

**Comment by dblock** [comment]
@colinjcahill looking forward to your pull request!
