### ISSUE TITLE
Incorrect xterm color map?

### ISSUE THREAD

**Issue by JoeMerten** [jenkinsci/ansicolor-plugin#93]
After wondering, why (blue) has been rendered to a bit unusual appearance, I'd checked the color values of  `AnsiColorMap XTerm` against the table in https://en.wikipedia.org/wiki/ANSI_escape_code and find some differences:

| Color Name     |AnsiColorMap|   wikipedia   |wikipedia hex| Comment |
|----------------|:----------:|:-------------:|:-------:|:-------:|
| Black          |  #000000   | 0, 0, 0       | #000000 | ok      |
| Red            |  #CD0000   | 205, 0, 0     | #D00000 | differs |
| Green          |  #00CD00   | 0, 205, 0     | #00D000 | differs |
| Brown / Yellow |  #CDCD00   | 205, 205, 0   | #D0D000 | differs |
| Blue           |  #1E90FF   | 0, 0, 238     | #0000EE | differs |
| Magenta        |  #CD00CD   | 205, 0, 205   | #D000D0 | differs |
| Cyan           |  #00CDCD   | 0, 205, 205   | #00D0D0 | differs |
| Gray           |  #E5E5E5   | 229, 229, 229 | #E5E5E5 | ok      |
| Dark Gray      |  #4C4C4C   | 127, 127, 127 | #7F7F7F | differs |
| Bright Red     |  #FF0000   | 255, 0, 0     | #FF0000 | ok      |
| Bright Green   |  #00FF00   | 0, 255, 0     | #00FF00 | ok      |
| Bright Yellow  |  #FFFF00   | 255, 255, 0   | #FFFF00 | ok      |
| Bright Blue    |  #4682B4   | 92, 92, 255   | #5C5CFF | differs |
| Bright Magenta |  #FF00FF   | 255, 0, 255   | #FF00FF | ok      |
| Bright Cyan    |  #00FFFF   | 0, 255, 255   | #00FFFF | ok      |
| White          |  #FFFFFF   | 255, 255, 255 | #FFFFFF | ok      |

Is there a reason why using different color values?
(Or maybe wikipedia is wrong?)

**Comment by Joe-Merten** [comment]
I'd now checked real live xterm on Kubuntu 16.04 (xterm version: 322-1ubuntu1).
And further, I find out, that I'd wrong calculated decimal 205 = 0xD0, as there is 205 = 0xCD instead.
So there were differences left just for the two blue colors and for dark gray:

| Color Name     |AnsiColorMap|  xterm  | wikipedia dec |wikipedia hex| Comment |
|----------------|:----------:|:-------:|:-------------:|:-------:|:-------:|
| Black          |  #000000   | #000000 | 0, 0, 0       | #000000 | ok      |
| Red            |  #CD0000   | #CD0000 | 205, 0, 0     | #CD0000 | ok      |
| Green          |  #00CD00   | #00CD00 | 0, 205, 0     | #00CD00 | ok      |
| Brown / Yellow |  #CDCD00   | #CDCD00 | 205, 205, 0   | #CDCD00 | ok      |
| Blue           |  #1E90FF   | #0000EE | 0, 0, 238     | #0000EE | differs |
| Magenta        |  #CD00CD   | #CD00CD | 205, 0, 205   | #CD00CD | ok      |
| Cyan           |  #00CDCD   | #00CDCD | 0, 205, 205   | #00CDCD | ok      |
| Gray           |  #E5E5E5   | #E5E5E5 | 229, 229, 229 | #E5E5E5 | ok      |
| Dark Gray      |  #4C4C4C   | #7F7F7F | 127, 127, 127 | #7F7F7F | differs |
| Bright Red     |  #FF0000   | #FF0000 | 255, 0, 0     | #FF0000 | ok      |
| Bright Green   |  #00FF00   | #00FF00 | 0, 255, 0     | #00FF00 | ok      |
| Bright Yellow  |  #FFFF00   | #FFFF00 | 255, 255, 0   | #FFFF00 | ok      |
| Bright Blue    |  #4682B4   | #5C5CFF | 92, 92, 255   | #5C5CFF | differs |
| Bright Magenta |  #FF00FF   | #FF00FF | 255, 0, 255   | #FF00FF | ok      |
| Bright Cyan    |  #00FFFF   | #00FFFF | 0, 255, 255   | #00FFFF | ok      |
| White          |  #FFFFFF   | #FFFFFF | 255, 255, 255 | #FFFFFF | ok      |

Note that the [wikipedia xterm 256 color chart](https://upload.wikimedia.org/wikipedia/commons/1/15/Xterm_256color_chart.svg) shows different values for the entries 0-15. 
In my above mentioned test (with xterm 322 on Kubuntu 16.04), I saw the same e.g. `#CD0000` for both `esc[31m` and `esc[38;5;1m` as were [wikipedia xterm 256 color chart](https://upload.wikimedia.org/wikipedia/commons/1/15/Xterm_256color_chart.svg) shows `#800000` instead.

**Comment by dblock** [comment]
I honestly don't know why we use one or the other. Maybe we can have all the variations? :)

**Comment by Joe-Merten** [comment]
For my thinking, if the scheme is named `xterm`, it should be map the same rgb color values as [xterm](http://web.archive.org/web/20130125000058/http://www.frexx.de/xterm-256-notes/) do.
I'd just double checked against [xterm-256-notes](http://web.archive.org/web/20130125000058/http://www.frexx.de/xterm-256-notes/) with the same results as in the table mentioned above.

So for the »Maybe we can have all the variations?« approach, it needs to add a scheme named like »slightliy modified xterm«. But is this really valuable? Hmm, maybe for users which depend on one or more of those 3 different colors and they might if they became different with the next update.

| Color Name     |AnsiColorMap|  xterm  | AnsiColorMap |xterm|
|----------------|:----------:|:-------:|:------------:|:---:|
| Blue           |  #1E90FF   | #0000EE | ![ansicolormap-blue](https://cloud.githubusercontent.com/assets/6552470/23630587/fe10f0d6-02bb-11e7-8516-9adbad3699ae.png) | ![xterm-blue](https://cloud.githubusercontent.com/assets/6552470/23630462/7fcdd126-02bb-11e7-959a-ec57d97235bf.png) |
| Dark Gray      |  #4C4C4C   | #7F7F7F | ![ansicolormap-dark-gray](https://cloud.githubusercontent.com/assets/6552470/23630622/0cff671c-02bc-11e7-9f78-18b67c375db0.png) | ![xterm-dark-gray](https://cloud.githubusercontent.com/assets/6552470/23630472/85e78ebc-02bb-11e7-84fb-a0e5b55aa850.png) |
| Bright Blue    |  #4682B4   | #5C5CFF | ![ansicolormap-bright-blue](https://cloud.githubusercontent.com/assets/6552470/23630636/17ed0d5a-02bc-11e7-9c10-a4172466f9d1.png) | ![xterm-bright-blue](https://cloud.githubusercontent.com/assets/6552470/23630476/8a3c33fa-02bb-11e7-8f3b-9ce7cc157209.png) |

(For me personally, its less important for the moment. Just want to make thinks working correct and intuitive as possible ;-)

**Comment by dblock** [comment]
I think by now you dug into this way more than anyone else @Joe-Merten, submit some PRs and we'll go with what you think is right until someone comments and disagrees?

**Comment by Joe-Merten** [comment]
Ok, let us wait for other peoples opinions.

**Comment by jacobweber** [comment]
For what it's worth, I found this plugin's gray (#4C4C4C) to be almost indistinguishable from black. I think you should go with the lighter #7F7F7F for that.
